sudo: false
language: go

services:
  - mysql

go:
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/fatih/color
  - go get github.com/golang/protobuf/proto
  - go get github.com/go-redis/redis
  - go get github.com/gorilla/websocket
  - go get github.com/go-ini/ini
  - go get google.golang.org/grpc
  - go get github.com/jinzhu/gorm
