sudo: false
language: go

services:
  - mysql

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/fatih/color
  - go get github.com/golang/protobuf/proto
