version: "3"

services:
  
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    hostname: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --data-path=/nsq_data --lookupd-tcp-address=nsqlookupd:4160 
    depends_on:
      - nsqlookupd
    hostname: nsqd
    volumes:
      - "./nsq_data/:/nsq_data"
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    hostname: nsqadmin
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

