version: "3"
services:
  ultimate-service:
    build: ./
    image: ultimate-service
    ports:
      - "7030:7030"
      - "8080:8080"
    volumes:
      - "./log/:/app/log"
      - "./config/:/app/config"
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "root:@(host.docker.internal:3306)/db_ultimate"
