version: "3"
services:
  ultimate-service:
    build: ./
    command: env GOOS=linux GOARCH=amd64 go build -o ultimate-service
    image: ultimate-service
    ports:
      - 7030:7030
      - 8088:8080
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "root:@(localhost:3306)/db_ultimate"


