version: "3"

services:

  consul:
    image: consul
    ports:
      - "8500:8500"
    volumes:
      - "./consul_data:/consul/data"
  
  ultimate-service-arena:
    build: game-service/
    image: ultimate-service-arena
    ports:
      - "3306"
      - "8080"
      - "50051"
    volumes:
      - "./log/:/log"
      - "./config/:/config"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "host.docker.internal:8500"
      MICRO_BROKER: "nsq"
      MICRO_BROKER_ADDRESS: "host.docker.internal:4150"
      # MICRO_TRANSPORT: "tcp"
      MYSQL_ADDR: "host.docker.internal"
    depends_on:
      - "consul"
      - "nsqd"
      - "nsqadmin"

  ultimate-service-game:
    build: arena-service/
    image: ultimate-service-game
    ports:
      - "7030:7030"
      - "3306"
      - "8080"
      - "50052"
    volumes:
      - "./log/:/log"
      - "./config/:/config"
    environment:
      MICRO_SERVER_ADDRESS: ":50052"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "host.docker.internal:8500"
      MICRO_BROKER: "nsq"
      MICRO_BROKER_ADDRESS: "host.docker.internal:4150"
      # MICRO_TRANSPORT: "tcp"
      MYSQL_ADDR: "host.docker.internal"
    depends_on:
      - "consul"
      - "nsqd"
      - "nsqadmin"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    hostname: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --data-path=/nsq_data --lookupd-tcp-address=nsqlookupd:4160 
    depends_on:
      - nsqlookupd
    hostname: nsqd
    volumes:
      - "./nsq_data/:/nsq_data"
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    hostname: nsqadmin
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

