version: "3"

services:
  
  ultimate-service-arena:
    build: game-service/
    image: ultimate-service-arena
    ports:
      - "3306"
      - "8080"
      - "8500"
    volumes:
      - "./log/:/log"
      - "./config/:/config"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
      MICRO_BROKER: "nsq"
      MICRO_BROKER_ADDRESS: "nsqd:4150"
      MYSQL_ADDR: "host.docker.internal"
    depends_on:
      - "consul"
      - "nsqd"

  ultimate-service-game:
    build: arena-service/
    image: ultimate-service-game
    ports:
      - "7030:7030"
      - "3306"
      - "8080"
      - "8500"
    volumes:
      - "./log/:/log"
      - "./config/:/config"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
      MICRO_BROKER: "nsq"
      MICRO_BROKER_ADDRESS: "nsqd:4150"
      MYSQL_ADDR: "host.docker.internal"
    depends_on:
      - "consul"
      - "nsqd"
      - "ultimate-service-arena"

  consul:
    image: consul
    hostname: consul
    ports:
      - "8500:8500"
    # volumes:
    #   - "./consul_data:/consul/data"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    hostname: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --data-path=/nsq_data -lookupd-tcp-address=nsqlookupd:4160 
    depends_on:
      - nsqlookupd
      - nsqadmin
    hostname: nsqd
    volumes:
      - "./nsq_data/:/nsq_data"
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin -lookupd-http-address=nsqlookupd:4161
    hostname: nsqadmin
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

