version: "3"
services:
  
  ultimate-service-arena:
    build: game-service/
    image: ultimate-service-arena
    ports:
      - "3306"
      - "8080"
      - "50051"
    volumes:
      - "./log/:/log"
      - "./config/:/config"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      MYSQL_ADDR: "host.docker.internal"
    depends_on:
      - "ultimate-service-game"

  ultimate-service-game:
    build: arena-service/
    image: ultimate-service-game
    ports:
      - "7030:7030"
      - "3306"
      - "8080"
      - "50052"
    volumes:
      - "./log/:/log"
      - "./config/:/config"
    environment:
      micro_server_address: ":50052"
      MICRO_REGISTRY: "mdns"
      MYSQL_ADDR: "host.docker.internal"

