// Code generated by protoc-gen-go. DO NOT EDIT.
// source: world/world.proto

package world

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MWU_WorldLogon struct {
	WorldId              uint32   `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	WorldName            string   `protobuf:"bytes,2,opt,name=world_name,json=worldName,proto3" json:"world_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_WorldLogon) Reset()         { *m = MWU_WorldLogon{} }
func (m *MWU_WorldLogon) String() string { return proto.CompactTextString(m) }
func (*MWU_WorldLogon) ProtoMessage()    {}
func (*MWU_WorldLogon) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{0}
}

func (m *MWU_WorldLogon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_WorldLogon.Unmarshal(m, b)
}
func (m *MWU_WorldLogon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_WorldLogon.Marshal(b, m, deterministic)
}
func (m *MWU_WorldLogon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_WorldLogon.Merge(m, src)
}
func (m *MWU_WorldLogon) XXX_Size() int {
	return xxx_messageInfo_MWU_WorldLogon.Size(m)
}
func (m *MWU_WorldLogon) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_WorldLogon.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_WorldLogon proto.InternalMessageInfo

func (m *MWU_WorldLogon) GetWorldId() uint32 {
	if m != nil {
		return m.WorldId
	}
	return 0
}

func (m *MWU_WorldLogon) GetWorldName() string {
	if m != nil {
		return m.WorldName
	}
	return ""
}

type MUW_WorldLogon struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_WorldLogon) Reset()         { *m = MUW_WorldLogon{} }
func (m *MUW_WorldLogon) String() string { return proto.CompactTextString(m) }
func (*MUW_WorldLogon) ProtoMessage()    {}
func (*MUW_WorldLogon) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{1}
}

func (m *MUW_WorldLogon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_WorldLogon.Unmarshal(m, b)
}
func (m *MUW_WorldLogon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_WorldLogon.Marshal(b, m, deterministic)
}
func (m *MUW_WorldLogon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_WorldLogon.Merge(m, src)
}
func (m *MUW_WorldLogon) XXX_Size() int {
	return xxx_messageInfo_MUW_WorldLogon.Size(m)
}
func (m *MUW_WorldLogon) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_WorldLogon.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_WorldLogon proto.InternalMessageInfo

type MWU_TestConnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_TestConnect) Reset()         { *m = MWU_TestConnect{} }
func (m *MWU_TestConnect) String() string { return proto.CompactTextString(m) }
func (*MWU_TestConnect) ProtoMessage()    {}
func (*MWU_TestConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{2}
}

func (m *MWU_TestConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_TestConnect.Unmarshal(m, b)
}
func (m *MWU_TestConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_TestConnect.Marshal(b, m, deterministic)
}
func (m *MWU_TestConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_TestConnect.Merge(m, src)
}
func (m *MWU_TestConnect) XXX_Size() int {
	return xxx_messageInfo_MWU_TestConnect.Size(m)
}
func (m *MWU_TestConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_TestConnect.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_TestConnect proto.InternalMessageInfo

type MUW_TestConnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_TestConnect) Reset()         { *m = MUW_TestConnect{} }
func (m *MUW_TestConnect) String() string { return proto.CompactTextString(m) }
func (*MUW_TestConnect) ProtoMessage()    {}
func (*MUW_TestConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{3}
}

func (m *MUW_TestConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_TestConnect.Unmarshal(m, b)
}
func (m *MUW_TestConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_TestConnect.Marshal(b, m, deterministic)
}
func (m *MUW_TestConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_TestConnect.Merge(m, src)
}
func (m *MUW_TestConnect) XXX_Size() int {
	return xxx_messageInfo_MUW_TestConnect.Size(m)
}
func (m *MUW_TestConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_TestConnect.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_TestConnect proto.InternalMessageInfo

type MWU_HeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_HeartBeat) Reset()         { *m = MWU_HeartBeat{} }
func (m *MWU_HeartBeat) String() string { return proto.CompactTextString(m) }
func (*MWU_HeartBeat) ProtoMessage()    {}
func (*MWU_HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{4}
}

func (m *MWU_HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_HeartBeat.Unmarshal(m, b)
}
func (m *MWU_HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_HeartBeat.Marshal(b, m, deterministic)
}
func (m *MWU_HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_HeartBeat.Merge(m, src)
}
func (m *MWU_HeartBeat) XXX_Size() int {
	return xxx_messageInfo_MWU_HeartBeat.Size(m)
}
func (m *MWU_HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_HeartBeat proto.InternalMessageInfo

type MUW_HeartBeat struct {
	BattleTime           uint32   `protobuf:"varint,1,opt,name=battle_time,json=battleTime,proto3" json:"battle_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_HeartBeat) Reset()         { *m = MUW_HeartBeat{} }
func (m *MUW_HeartBeat) String() string { return proto.CompactTextString(m) }
func (*MUW_HeartBeat) ProtoMessage()    {}
func (*MUW_HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{5}
}

func (m *MUW_HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_HeartBeat.Unmarshal(m, b)
}
func (m *MUW_HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_HeartBeat.Marshal(b, m, deterministic)
}
func (m *MUW_HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_HeartBeat.Merge(m, src)
}
func (m *MUW_HeartBeat) XXX_Size() int {
	return xxx_messageInfo_MUW_HeartBeat.Size(m)
}
func (m *MUW_HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_HeartBeat proto.InternalMessageInfo

func (m *MUW_HeartBeat) GetBattleTime() uint32 {
	if m != nil {
		return m.BattleTime
	}
	return 0
}

type MWU_WorldConnected struct {
	WorldId              []uint32 `protobuf:"varint,1,rep,packed,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_WorldConnected) Reset()         { *m = MWU_WorldConnected{} }
func (m *MWU_WorldConnected) String() string { return proto.CompactTextString(m) }
func (*MWU_WorldConnected) ProtoMessage()    {}
func (*MWU_WorldConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{6}
}

func (m *MWU_WorldConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_WorldConnected.Unmarshal(m, b)
}
func (m *MWU_WorldConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_WorldConnected.Marshal(b, m, deterministic)
}
func (m *MWU_WorldConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_WorldConnected.Merge(m, src)
}
func (m *MWU_WorldConnected) XXX_Size() int {
	return xxx_messageInfo_MWU_WorldConnected.Size(m)
}
func (m *MWU_WorldConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_WorldConnected.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_WorldConnected proto.InternalMessageInfo

func (m *MWU_WorldConnected) GetWorldId() []uint32 {
	if m != nil {
		return m.WorldId
	}
	return nil
}

type MUW_RequestPlayerInfo struct {
	MinLevel             int32    `protobuf:"varint,1,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestPlayerInfo) Reset()         { *m = MUW_RequestPlayerInfo{} }
func (m *MUW_RequestPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestPlayerInfo) ProtoMessage()    {}
func (*MUW_RequestPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{7}
}

func (m *MUW_RequestPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Unmarshal(m, b)
}
func (m *MUW_RequestPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MUW_RequestPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestPlayerInfo.Merge(m, src)
}
func (m *MUW_RequestPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Size(m)
}
func (m *MUW_RequestPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestPlayerInfo proto.InternalMessageInfo

func (m *MUW_RequestPlayerInfo) GetMinLevel() int32 {
	if m != nil {
		return m.MinLevel
	}
	return 0
}

type MUW_RequestGuildInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestGuildInfo) Reset()         { *m = MUW_RequestGuildInfo{} }
func (m *MUW_RequestGuildInfo) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestGuildInfo) ProtoMessage()    {}
func (*MUW_RequestGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2154e1c0b2e786c2, []int{8}
}

func (m *MUW_RequestGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestGuildInfo.Unmarshal(m, b)
}
func (m *MUW_RequestGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestGuildInfo.Marshal(b, m, deterministic)
}
func (m *MUW_RequestGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestGuildInfo.Merge(m, src)
}
func (m *MUW_RequestGuildInfo) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestGuildInfo.Size(m)
}
func (m *MUW_RequestGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestGuildInfo proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MWU_WorldLogon)(nil), "world.MWU_WorldLogon")
	proto.RegisterType((*MUW_WorldLogon)(nil), "world.MUW_WorldLogon")
	proto.RegisterType((*MWU_TestConnect)(nil), "world.MWU_TestConnect")
	proto.RegisterType((*MUW_TestConnect)(nil), "world.MUW_TestConnect")
	proto.RegisterType((*MWU_HeartBeat)(nil), "world.MWU_HeartBeat")
	proto.RegisterType((*MUW_HeartBeat)(nil), "world.MUW_HeartBeat")
	proto.RegisterType((*MWU_WorldConnected)(nil), "world.MWU_WorldConnected")
	proto.RegisterType((*MUW_RequestPlayerInfo)(nil), "world.MUW_RequestPlayerInfo")
	proto.RegisterType((*MUW_RequestGuildInfo)(nil), "world.MUW_RequestGuildInfo")
}

func init() { proto.RegisterFile("world/world.proto", fileDescriptor_2154e1c0b2e786c2) }

var fileDescriptor_2154e1c0b2e786c2 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x52, 0x6d, 0x46, 0xd2, 0xda, 0x45, 0xa5, 0x22, 0x62, 0xd9, 0x53, 0x4f, 0x56,
	0xd0, 0x4f, 0xa0, 0x07, 0xad, 0xb4, 0x22, 0xa1, 0x21, 0xc7, 0xb0, 0x75, 0x47, 0x59, 0xd8, 0x3f,
	0x9a, 0x4e, 0x15, 0xbf, 0xbd, 0xec, 0xb4, 0x84, 0xd8, 0xcb, 0xc2, 0xfb, 0xcd, 0xcc, 0x9b, 0x7d,
	0x03, 0x83, 0x9f, 0x50, 0x5b, 0x3d, 0xe1, 0xf7, 0xfa, 0xb3, 0x0e, 0x14, 0x44, 0x87, 0x85, 0x7c,
	0x86, 0xde, 0xbc, 0x2c, 0xaa, 0x32, 0x8a, 0x59, 0xf8, 0x08, 0x5e, 0x9c, 0x43, 0x97, 0x4b, 0x95,
	0xd1, 0xc3, 0x64, 0x94, 0x8c, 0xb3, 0xfc, 0x90, 0xf5, 0x54, 0x8b, 0x4b, 0x80, 0x4d, 0xc9, 0x2b,
	0x87, 0xc3, 0xbd, 0x51, 0x32, 0x4e, 0xf3, 0x94, 0xc9, 0x8b, 0x72, 0x28, 0x8f, 0xa1, 0x37, 0x2f,
	0xca, 0x96, 0x97, 0x1c, 0x40, 0x3f, 0xba, 0x2f, 0x70, 0x45, 0x0f, 0xc1, 0x7b, 0x7c, 0x23, 0x46,
	0x45, 0xf9, 0x0f, 0xf5, 0x21, 0x8b, 0x5d, 0x4f, 0xa8, 0x6a, 0xba, 0x47, 0x45, 0xf2, 0x06, 0xb2,
	0xd8, 0xd3, 0x00, 0x71, 0x05, 0x47, 0x4b, 0x45, 0x64, 0xb1, 0x22, 0xe3, 0x70, 0xfb, 0x2d, 0xd8,
	0xa0, 0x85, 0x71, 0x28, 0x27, 0x20, 0x9a, 0x18, 0x5b, 0x5b, 0xd4, 0x3b, 0x51, 0xf6, 0x5b, 0x51,
	0xe4, 0x1d, 0x9c, 0xc6, 0x15, 0x39, 0x7e, 0xad, 0x71, 0x45, 0xaf, 0x56, 0xfd, 0x62, 0x3d, 0xf5,
	0xef, 0x41, 0x5c, 0x40, 0xea, 0x8c, 0xaf, 0x2c, 0x7e, 0xa3, 0xe5, 0x45, 0x9d, 0xbc, 0xeb, 0x8c,
	0x9f, 0x45, 0x2d, 0xcf, 0xe0, 0xa4, 0x35, 0xf5, 0xb8, 0x36, 0x56, 0xc7, 0xa1, 0xe5, 0x01, 0xdf,
	0xf4, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x21, 0xaf, 0x5e, 0xc2, 0x68, 0x01, 0x00, 0x00,
}
