// Code generated by protoc-gen-go. DO NOT EDIT.
// source: world_message.proto

package world_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MWU_WorldLogon struct {
	WorldId              uint32   `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	WorldName            string   `protobuf:"bytes,2,opt,name=world_name,json=worldName,proto3" json:"world_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_WorldLogon) Reset()         { *m = MWU_WorldLogon{} }
func (m *MWU_WorldLogon) String() string { return proto.CompactTextString(m) }
func (*MWU_WorldLogon) ProtoMessage()    {}
func (*MWU_WorldLogon) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{0}
}

func (m *MWU_WorldLogon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_WorldLogon.Unmarshal(m, b)
}
func (m *MWU_WorldLogon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_WorldLogon.Marshal(b, m, deterministic)
}
func (m *MWU_WorldLogon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_WorldLogon.Merge(m, src)
}
func (m *MWU_WorldLogon) XXX_Size() int {
	return xxx_messageInfo_MWU_WorldLogon.Size(m)
}
func (m *MWU_WorldLogon) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_WorldLogon.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_WorldLogon proto.InternalMessageInfo

func (m *MWU_WorldLogon) GetWorldId() uint32 {
	if m != nil {
		return m.WorldId
	}
	return 0
}

func (m *MWU_WorldLogon) GetWorldName() string {
	if m != nil {
		return m.WorldName
	}
	return ""
}

type MUW_WorldLogon struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_WorldLogon) Reset()         { *m = MUW_WorldLogon{} }
func (m *MUW_WorldLogon) String() string { return proto.CompactTextString(m) }
func (*MUW_WorldLogon) ProtoMessage()    {}
func (*MUW_WorldLogon) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{1}
}

func (m *MUW_WorldLogon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_WorldLogon.Unmarshal(m, b)
}
func (m *MUW_WorldLogon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_WorldLogon.Marshal(b, m, deterministic)
}
func (m *MUW_WorldLogon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_WorldLogon.Merge(m, src)
}
func (m *MUW_WorldLogon) XXX_Size() int {
	return xxx_messageInfo_MUW_WorldLogon.Size(m)
}
func (m *MUW_WorldLogon) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_WorldLogon.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_WorldLogon proto.InternalMessageInfo

type MWU_TestConnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_TestConnect) Reset()         { *m = MWU_TestConnect{} }
func (m *MWU_TestConnect) String() string { return proto.CompactTextString(m) }
func (*MWU_TestConnect) ProtoMessage()    {}
func (*MWU_TestConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{2}
}

func (m *MWU_TestConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_TestConnect.Unmarshal(m, b)
}
func (m *MWU_TestConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_TestConnect.Marshal(b, m, deterministic)
}
func (m *MWU_TestConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_TestConnect.Merge(m, src)
}
func (m *MWU_TestConnect) XXX_Size() int {
	return xxx_messageInfo_MWU_TestConnect.Size(m)
}
func (m *MWU_TestConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_TestConnect.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_TestConnect proto.InternalMessageInfo

type MUW_TestConnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_TestConnect) Reset()         { *m = MUW_TestConnect{} }
func (m *MUW_TestConnect) String() string { return proto.CompactTextString(m) }
func (*MUW_TestConnect) ProtoMessage()    {}
func (*MUW_TestConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{3}
}

func (m *MUW_TestConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_TestConnect.Unmarshal(m, b)
}
func (m *MUW_TestConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_TestConnect.Marshal(b, m, deterministic)
}
func (m *MUW_TestConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_TestConnect.Merge(m, src)
}
func (m *MUW_TestConnect) XXX_Size() int {
	return xxx_messageInfo_MUW_TestConnect.Size(m)
}
func (m *MUW_TestConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_TestConnect.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_TestConnect proto.InternalMessageInfo

type MWU_HeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_HeartBeat) Reset()         { *m = MWU_HeartBeat{} }
func (m *MWU_HeartBeat) String() string { return proto.CompactTextString(m) }
func (*MWU_HeartBeat) ProtoMessage()    {}
func (*MWU_HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{4}
}

func (m *MWU_HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_HeartBeat.Unmarshal(m, b)
}
func (m *MWU_HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_HeartBeat.Marshal(b, m, deterministic)
}
func (m *MWU_HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_HeartBeat.Merge(m, src)
}
func (m *MWU_HeartBeat) XXX_Size() int {
	return xxx_messageInfo_MWU_HeartBeat.Size(m)
}
func (m *MWU_HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_HeartBeat proto.InternalMessageInfo

type MUW_HeartBeat struct {
	BattleTime           uint32   `protobuf:"varint,1,opt,name=battle_time,json=battleTime,proto3" json:"battle_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_HeartBeat) Reset()         { *m = MUW_HeartBeat{} }
func (m *MUW_HeartBeat) String() string { return proto.CompactTextString(m) }
func (*MUW_HeartBeat) ProtoMessage()    {}
func (*MUW_HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{5}
}

func (m *MUW_HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_HeartBeat.Unmarshal(m, b)
}
func (m *MUW_HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_HeartBeat.Marshal(b, m, deterministic)
}
func (m *MUW_HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_HeartBeat.Merge(m, src)
}
func (m *MUW_HeartBeat) XXX_Size() int {
	return xxx_messageInfo_MUW_HeartBeat.Size(m)
}
func (m *MUW_HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_HeartBeat proto.InternalMessageInfo

func (m *MUW_HeartBeat) GetBattleTime() uint32 {
	if m != nil {
		return m.BattleTime
	}
	return 0
}

type MWU_WorldConnected struct {
	WorldId              []uint32 `protobuf:"varint,1,rep,packed,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_WorldConnected) Reset()         { *m = MWU_WorldConnected{} }
func (m *MWU_WorldConnected) String() string { return proto.CompactTextString(m) }
func (*MWU_WorldConnected) ProtoMessage()    {}
func (*MWU_WorldConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{6}
}

func (m *MWU_WorldConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_WorldConnected.Unmarshal(m, b)
}
func (m *MWU_WorldConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_WorldConnected.Marshal(b, m, deterministic)
}
func (m *MWU_WorldConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_WorldConnected.Merge(m, src)
}
func (m *MWU_WorldConnected) XXX_Size() int {
	return xxx_messageInfo_MWU_WorldConnected.Size(m)
}
func (m *MWU_WorldConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_WorldConnected.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_WorldConnected proto.InternalMessageInfo

func (m *MWU_WorldConnected) GetWorldId() []uint32 {
	if m != nil {
		return m.WorldId
	}
	return nil
}

type MUW_RequestPlayerInfo struct {
	MinLevel             int32    `protobuf:"varint,1,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestPlayerInfo) Reset()         { *m = MUW_RequestPlayerInfo{} }
func (m *MUW_RequestPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestPlayerInfo) ProtoMessage()    {}
func (*MUW_RequestPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{7}
}

func (m *MUW_RequestPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Unmarshal(m, b)
}
func (m *MUW_RequestPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MUW_RequestPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestPlayerInfo.Merge(m, src)
}
func (m *MUW_RequestPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Size(m)
}
func (m *MUW_RequestPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestPlayerInfo proto.InternalMessageInfo

func (m *MUW_RequestPlayerInfo) GetMinLevel() int32 {
	if m != nil {
		return m.MinLevel
	}
	return 0
}

type CrossPlayerInfo struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerId             uint32   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Gender               int32    `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Race                 int32    `protobuf:"varint,5,opt,name=race,proto3" json:"race,omitempty"`
	HeadProtrait         int32    `protobuf:"varint,6,opt,name=head_protrait,json=headProtrait,proto3" json:"head_protrait,omitempty"`
	HeadQuality          int32    `protobuf:"varint,7,opt,name=head_quality,json=headQuality,proto3" json:"head_quality,omitempty"`
	PlayerName           string   `protobuf:"bytes,8,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	GuildId              int64    `protobuf:"varint,9,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	LastLogoffTime       uint32   `protobuf:"varint,10,opt,name=last_logoff_time,json=lastLogoffTime,proto3" json:"last_logoff_time,omitempty"`
	Online               bool     `protobuf:"varint,11,opt,name=online,proto3" json:"online,omitempty"`
	Level                int32    `protobuf:"varint,12,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel             int32    `protobuf:"varint,13,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	PlayerScore          int32    `protobuf:"varint,14,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	HistoryScore         int32    `protobuf:"varint,15,opt,name=history_score,json=historyScore,proto3" json:"history_score,omitempty"`
	RemainsFloor         int32    `protobuf:"varint,16,opt,name=remains_floor,json=remainsFloor,proto3" json:"remains_floor,omitempty"`
	HeroTypeId           []uint32 `protobuf:"varint,17,rep,packed,name=hero_type_id,json=heroTypeId,proto3" json:"hero_type_id,omitempty"`
	FashionId            []uint32 `protobuf:"varint,18,rep,packed,name=fashion_id,json=fashionId,proto3" json:"fashion_id,omitempty"`
	MountTypeId          []uint32 `protobuf:"varint,19,rep,packed,name=mount_type_id,json=mountTypeId,proto3" json:"mount_type_id,omitempty"`
	RuneTypeId           []uint32 `protobuf:"varint,20,rep,packed,name=rune_type_id,json=runeTypeId,proto3" json:"rune_type_id,omitempty"`
	StateFlag            []int32  `protobuf:"varint,21,rep,packed,name=state_flag,json=stateFlag,proto3" json:"state_flag,omitempty"`
	PeakLevel            int32    `protobuf:"varint,22,opt,name=peak_level,json=peakLevel,proto3" json:"peak_level,omitempty"`
	PlayerStatus         uint32   `protobuf:"varint,23,opt,name=player_status,json=playerStatus,proto3" json:"player_status,omitempty"`
	CurDecorate          int32    `protobuf:"varint,24,opt,name=cur_decorate,json=curDecorate,proto3" json:"cur_decorate,omitempty"`
	ReturnPlayerId       int64    `protobuf:"varint,25,opt,name=return_player_id,json=returnPlayerId,proto3" json:"return_player_id,omitempty"`
	LastSquareActionTime uint32   `protobuf:"varint,26,opt,name=last_square_action_time,json=lastSquareActionTime,proto3" json:"last_square_action_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossPlayerInfo) Reset()         { *m = CrossPlayerInfo{} }
func (m *CrossPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CrossPlayerInfo) ProtoMessage()    {}
func (*CrossPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{8}
}

func (m *CrossPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossPlayerInfo.Unmarshal(m, b)
}
func (m *CrossPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossPlayerInfo.Marshal(b, m, deterministic)
}
func (m *CrossPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossPlayerInfo.Merge(m, src)
}
func (m *CrossPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CrossPlayerInfo.Size(m)
}
func (m *CrossPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CrossPlayerInfo proto.InternalMessageInfo

func (m *CrossPlayerInfo) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *CrossPlayerInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CrossPlayerInfo) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *CrossPlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *CrossPlayerInfo) GetRace() int32 {
	if m != nil {
		return m.Race
	}
	return 0
}

func (m *CrossPlayerInfo) GetHeadProtrait() int32 {
	if m != nil {
		return m.HeadProtrait
	}
	return 0
}

func (m *CrossPlayerInfo) GetHeadQuality() int32 {
	if m != nil {
		return m.HeadQuality
	}
	return 0
}

func (m *CrossPlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *CrossPlayerInfo) GetGuildId() int64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *CrossPlayerInfo) GetLastLogoffTime() uint32 {
	if m != nil {
		return m.LastLogoffTime
	}
	return 0
}

func (m *CrossPlayerInfo) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *CrossPlayerInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *CrossPlayerInfo) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *CrossPlayerInfo) GetPlayerScore() int32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *CrossPlayerInfo) GetHistoryScore() int32 {
	if m != nil {
		return m.HistoryScore
	}
	return 0
}

func (m *CrossPlayerInfo) GetRemainsFloor() int32 {
	if m != nil {
		return m.RemainsFloor
	}
	return 0
}

func (m *CrossPlayerInfo) GetHeroTypeId() []uint32 {
	if m != nil {
		return m.HeroTypeId
	}
	return nil
}

func (m *CrossPlayerInfo) GetFashionId() []uint32 {
	if m != nil {
		return m.FashionId
	}
	return nil
}

func (m *CrossPlayerInfo) GetMountTypeId() []uint32 {
	if m != nil {
		return m.MountTypeId
	}
	return nil
}

func (m *CrossPlayerInfo) GetRuneTypeId() []uint32 {
	if m != nil {
		return m.RuneTypeId
	}
	return nil
}

func (m *CrossPlayerInfo) GetStateFlag() []int32 {
	if m != nil {
		return m.StateFlag
	}
	return nil
}

func (m *CrossPlayerInfo) GetPeakLevel() int32 {
	if m != nil {
		return m.PeakLevel
	}
	return 0
}

func (m *CrossPlayerInfo) GetPlayerStatus() uint32 {
	if m != nil {
		return m.PlayerStatus
	}
	return 0
}

func (m *CrossPlayerInfo) GetCurDecorate() int32 {
	if m != nil {
		return m.CurDecorate
	}
	return 0
}

func (m *CrossPlayerInfo) GetReturnPlayerId() int64 {
	if m != nil {
		return m.ReturnPlayerId
	}
	return 0
}

func (m *CrossPlayerInfo) GetLastSquareActionTime() uint32 {
	if m != nil {
		return m.LastSquareActionTime
	}
	return 0
}

type MWU_RequestPlayerInfo struct {
	Info                 []*CrossPlayerInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MWU_RequestPlayerInfo) Reset()         { *m = MWU_RequestPlayerInfo{} }
func (m *MWU_RequestPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MWU_RequestPlayerInfo) ProtoMessage()    {}
func (*MWU_RequestPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{9}
}

func (m *MWU_RequestPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_RequestPlayerInfo.Unmarshal(m, b)
}
func (m *MWU_RequestPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_RequestPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MWU_RequestPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_RequestPlayerInfo.Merge(m, src)
}
func (m *MWU_RequestPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MWU_RequestPlayerInfo.Size(m)
}
func (m *MWU_RequestPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_RequestPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_RequestPlayerInfo proto.InternalMessageInfo

func (m *MWU_RequestPlayerInfo) GetInfo() []*CrossPlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MUW_RequestGuildInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestGuildInfo) Reset()         { *m = MUW_RequestGuildInfo{} }
func (m *MUW_RequestGuildInfo) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestGuildInfo) ProtoMessage()    {}
func (*MUW_RequestGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{10}
}

func (m *MUW_RequestGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestGuildInfo.Unmarshal(m, b)
}
func (m *MUW_RequestGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestGuildInfo.Marshal(b, m, deterministic)
}
func (m *MUW_RequestGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestGuildInfo.Merge(m, src)
}
func (m *MUW_RequestGuildInfo) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestGuildInfo.Size(m)
}
func (m *MUW_RequestGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestGuildInfo proto.InternalMessageInfo

type CrossGuildInfo struct {
	GuildId              int64    `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GuildName            string   `protobuf:"bytes,2,opt,name=guild_name,json=guildName,proto3" json:"guild_name,omitempty"`
	ServerId             uint32   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MasterId             int64    `protobuf:"varint,4,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	MasterName           string   `protobuf:"bytes,5,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	CreateTime           uint32   `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	HallLevel            int32    `protobuf:"varint,7,opt,name=hall_level,json=hallLevel,proto3" json:"hall_level,omitempty"`
	Score                int32    `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	CastleScore          int32    `protobuf:"varint,9,opt,name=castle_score,json=castleScore,proto3" json:"castle_score,omitempty"`
	MemberNum            int32    `protobuf:"varint,10,opt,name=member_num,json=memberNum,proto3" json:"member_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossGuildInfo) Reset()         { *m = CrossGuildInfo{} }
func (m *CrossGuildInfo) String() string { return proto.CompactTextString(m) }
func (*CrossGuildInfo) ProtoMessage()    {}
func (*CrossGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{11}
}

func (m *CrossGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossGuildInfo.Unmarshal(m, b)
}
func (m *CrossGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossGuildInfo.Marshal(b, m, deterministic)
}
func (m *CrossGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossGuildInfo.Merge(m, src)
}
func (m *CrossGuildInfo) XXX_Size() int {
	return xxx_messageInfo_CrossGuildInfo.Size(m)
}
func (m *CrossGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CrossGuildInfo proto.InternalMessageInfo

func (m *CrossGuildInfo) GetGuildId() int64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *CrossGuildInfo) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *CrossGuildInfo) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *CrossGuildInfo) GetMasterId() int64 {
	if m != nil {
		return m.MasterId
	}
	return 0
}

func (m *CrossGuildInfo) GetMasterName() string {
	if m != nil {
		return m.MasterName
	}
	return ""
}

func (m *CrossGuildInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *CrossGuildInfo) GetHallLevel() int32 {
	if m != nil {
		return m.HallLevel
	}
	return 0
}

func (m *CrossGuildInfo) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *CrossGuildInfo) GetCastleScore() int32 {
	if m != nil {
		return m.CastleScore
	}
	return 0
}

func (m *CrossGuildInfo) GetMemberNum() int32 {
	if m != nil {
		return m.MemberNum
	}
	return 0
}

type MWU_RequestGuildInfo struct {
	Info                 []*CrossGuildInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MWU_RequestGuildInfo) Reset()         { *m = MWU_RequestGuildInfo{} }
func (m *MWU_RequestGuildInfo) String() string { return proto.CompactTextString(m) }
func (*MWU_RequestGuildInfo) ProtoMessage()    {}
func (*MWU_RequestGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33865c398800497b, []int{12}
}

func (m *MWU_RequestGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_RequestGuildInfo.Unmarshal(m, b)
}
func (m *MWU_RequestGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_RequestGuildInfo.Marshal(b, m, deterministic)
}
func (m *MWU_RequestGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_RequestGuildInfo.Merge(m, src)
}
func (m *MWU_RequestGuildInfo) XXX_Size() int {
	return xxx_messageInfo_MWU_RequestGuildInfo.Size(m)
}
func (m *MWU_RequestGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_RequestGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_RequestGuildInfo proto.InternalMessageInfo

func (m *MWU_RequestGuildInfo) GetInfo() []*CrossGuildInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*MWU_WorldLogon)(nil), "world_message.MWU_WorldLogon")
	proto.RegisterType((*MUW_WorldLogon)(nil), "world_message.MUW_WorldLogon")
	proto.RegisterType((*MWU_TestConnect)(nil), "world_message.MWU_TestConnect")
	proto.RegisterType((*MUW_TestConnect)(nil), "world_message.MUW_TestConnect")
	proto.RegisterType((*MWU_HeartBeat)(nil), "world_message.MWU_HeartBeat")
	proto.RegisterType((*MUW_HeartBeat)(nil), "world_message.MUW_HeartBeat")
	proto.RegisterType((*MWU_WorldConnected)(nil), "world_message.MWU_WorldConnected")
	proto.RegisterType((*MUW_RequestPlayerInfo)(nil), "world_message.MUW_RequestPlayerInfo")
	proto.RegisterType((*CrossPlayerInfo)(nil), "world_message.CrossPlayerInfo")
	proto.RegisterType((*MWU_RequestPlayerInfo)(nil), "world_message.MWU_RequestPlayerInfo")
	proto.RegisterType((*MUW_RequestGuildInfo)(nil), "world_message.MUW_RequestGuildInfo")
	proto.RegisterType((*CrossGuildInfo)(nil), "world_message.CrossGuildInfo")
	proto.RegisterType((*MWU_RequestGuildInfo)(nil), "world_message.MWU_RequestGuildInfo")
}

func init() { proto.RegisterFile("world_message.proto", fileDescriptor_33865c398800497b) }

var fileDescriptor_33865c398800497b = []byte{
	// 835 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0xe1, 0x72, 0xdb, 0x44,
	0x10, 0xc7, 0xc7, 0x4d, 0xec, 0x58, 0xeb, 0xd8, 0x49, 0xaf, 0x4e, 0xa2, 0xc2, 0x98, 0x1a, 0xf5,
	0x8b, 0x3f, 0x15, 0x28, 0xf0, 0x00, 0x50, 0xa6, 0x20, 0x48, 0x3b, 0x41, 0x49, 0x26, 0x1f, 0x35,
	0x17, 0x6b, 0xed, 0x68, 0x90, 0x74, 0xce, 0xdd, 0x29, 0x8c, 0x1f, 0x8e, 0xb7, 0xe1, 0x41, 0x98,
	0xdd, 0xbd, 0x38, 0x76, 0x61, 0xf8, 0x96, 0xfd, 0xed, 0xfa, 0x74, 0xfb, 0xff, 0xef, 0x5e, 0xe0,
	0xc5, 0x9f, 0xc6, 0x56, 0x45, 0x5e, 0xa3, 0x73, 0x7a, 0x89, 0x6f, 0x56, 0xd6, 0x78, 0xa3, 0x86,
	0x3b, 0x30, 0xf9, 0x15, 0x46, 0x1f, 0x6e, 0xae, 0xf3, 0x1b, 0x82, 0xe7, 0x66, 0x69, 0x1a, 0xf5,
	0x12, 0xfa, 0x52, 0x52, 0x16, 0x71, 0x67, 0xda, 0x99, 0x0d, 0xb3, 0x03, 0x8e, 0xd3, 0x42, 0x4d,
	0x00, 0x24, 0xd5, 0xe8, 0x1a, 0xe3, 0x67, 0xd3, 0xce, 0x2c, 0xca, 0x22, 0x26, 0x1f, 0x75, 0x8d,
	0xc9, 0x31, 0x8c, 0x3e, 0x5c, 0xdf, 0x6c, 0x9d, 0x95, 0x3c, 0x87, 0x23, 0x3a, 0xfd, 0x0a, 0x9d,
	0x7f, 0x67, 0x9a, 0x06, 0xe7, 0x9e, 0xd1, 0xf5, 0xcd, 0x0e, 0x3a, 0x82, 0x21, 0x55, 0xfd, 0x82,
	0xda, 0xfa, 0x1f, 0x51, 0xfb, 0xe4, 0x6b, 0x18, 0x52, 0xcd, 0x06, 0xa8, 0x57, 0x30, 0xb8, 0xd5,
	0xde, 0x57, 0x98, 0xfb, 0xb2, 0xc6, 0x70, 0x2d, 0x10, 0x74, 0x55, 0xd6, 0x98, 0x7c, 0x05, 0x6a,
	0xd3, 0x46, 0x38, 0x16, 0x8b, 0x4f, 0x5a, 0xd9, 0xdb, 0x6a, 0x25, 0xf9, 0x0e, 0x4e, 0xe8, 0x13,
	0x19, 0xde, 0xb7, 0xe8, 0xfc, 0x45, 0xa5, 0xd7, 0x68, 0xd3, 0x66, 0x61, 0xd4, 0xe7, 0x10, 0xd5,
	0x65, 0x93, 0x57, 0xf8, 0x80, 0x15, 0x7f, 0xa8, 0x9b, 0xf5, 0xeb, 0xb2, 0x39, 0xa7, 0x38, 0xf9,
	0xbb, 0x07, 0x47, 0xef, 0xac, 0x71, 0x6e, 0xf7, 0x07, 0x2b, 0x8e, 0x1e, 0x05, 0xdb, 0xcb, 0xfa,
	0x02, 0xd2, 0x42, 0x9d, 0xc1, 0x41, 0xeb, 0x24, 0x25, 0x72, 0xf5, 0x28, 0x4c, 0x0b, 0xfa, 0x95,
	0x43, 0xfb, 0x20, 0xa9, 0x3d, 0xee, 0xa7, 0x2f, 0x20, 0x2d, 0xd4, 0x29, 0xf4, 0x96, 0xd8, 0x14,
	0x68, 0xe3, 0x7d, 0xbe, 0x40, 0x88, 0x94, 0x82, 0x7d, 0xab, 0xe7, 0x18, 0x77, 0x99, 0xf2, 0xdf,
	0xea, 0x35, 0x0c, 0xef, 0x50, 0x17, 0x39, 0xb9, 0x6b, 0x75, 0xe9, 0xe3, 0x1e, 0x27, 0x0f, 0x09,
	0x5e, 0x04, 0xa6, 0xbe, 0x04, 0x8e, 0xf3, 0xfb, 0x56, 0x57, 0xa5, 0x5f, 0xc7, 0x07, 0x5c, 0x33,
	0x20, 0xf6, 0xbb, 0x20, 0x92, 0x38, 0xb4, 0xc1, 0xe6, 0xf6, 0xf9, 0xb6, 0x20, 0x88, 0xdc, 0x25,
	0x31, 0x97, 0x6d, 0x29, 0x62, 0x46, 0xdc, 0xe6, 0x01, 0xc7, 0x69, 0xa1, 0x66, 0x70, 0x5c, 0x69,
	0xe7, 0xf3, 0xca, 0x2c, 0xcd, 0x62, 0x21, 0x1e, 0x01, 0xf7, 0x34, 0x22, 0x7e, 0xce, 0x98, 0x7c,
	0xa2, 0xce, 0x4c, 0x53, 0x95, 0x0d, 0xc6, 0x83, 0x69, 0x67, 0xd6, 0xcf, 0x42, 0xa4, 0xc6, 0xd0,
	0x15, 0xc5, 0x0f, 0xf9, 0x66, 0x12, 0x90, 0x48, 0x0f, 0xe5, 0x2a, 0x78, 0x31, 0x14, 0x2f, 0x1e,
	0xca, 0x15, 0x7b, 0x41, 0x3d, 0x85, 0x0b, 0xbb, 0xb9, 0xb1, 0x18, 0x8f, 0xa4, 0x27, 0x61, 0x97,
	0x84, 0x58, 0x9b, 0xd2, 0x79, 0x63, 0xd7, 0xa1, 0xe6, 0x28, 0x68, 0x23, 0x70, 0x53, 0x64, 0xb1,
	0xd6, 0x65, 0xe3, 0xf2, 0x45, 0x65, 0x8c, 0x8d, 0x8f, 0xa5, 0x28, 0xc0, 0xf7, 0xc4, 0xd4, 0x94,
	0x04, 0xb4, 0x26, 0xf7, 0xeb, 0x15, 0x92, 0x00, 0xcf, 0x79, 0x9a, 0x80, 0xd8, 0xd5, 0x7a, 0x85,
	0xb2, 0x1b, 0x0b, 0xed, 0xee, 0x4a, 0xd3, 0x50, 0x5e, 0x71, 0x3e, 0x0a, 0x24, 0x2d, 0x54, 0x02,
	0xc3, 0xda, 0xb4, 0x8d, 0xdf, 0x9c, 0xf0, 0x82, 0x2b, 0x06, 0x0c, 0xc3, 0x11, 0x53, 0x38, 0xb4,
	0x6d, 0x83, 0x9b, 0x92, 0xb1, 0x7c, 0x84, 0xd8, 0xd3, 0x47, 0x9c, 0xd7, 0x1e, 0xf3, 0x45, 0xa5,
	0x97, 0xf1, 0xc9, 0x74, 0x6f, 0xd6, 0xcd, 0x22, 0x26, 0xef, 0x2b, 0xbd, 0xa4, 0xf4, 0x0a, 0xf5,
	0x1f, 0x41, 0xb0, 0x53, 0xee, 0x23, 0x22, 0x22, 0x8a, 0xbd, 0x86, 0xe1, 0xa3, 0x62, 0x5e, 0xfb,
	0xd6, 0xc5, 0x67, 0xec, 0x51, 0x90, 0xf1, 0x92, 0x19, 0xc9, 0x3a, 0x6f, 0x6d, 0x5e, 0xe0, 0xdc,
	0x58, 0xed, 0x31, 0x8e, 0x45, 0xd6, 0x79, 0x6b, 0x7f, 0x0a, 0x88, 0xec, 0xb6, 0xe8, 0x5b, 0xdb,
	0xe4, 0x4f, 0x83, 0xff, 0x92, 0x27, 0x62, 0x24, 0xfc, 0xe2, 0x71, 0xfc, 0xbf, 0x87, 0x33, 0x1e,
	0x0c, 0x77, 0xdf, 0x6a, 0x8b, 0xb9, 0x9e, 0x7b, 0xd2, 0x87, 0xe7, 0xe3, 0x33, 0xfe, 0xf6, 0x98,
	0xd2, 0x97, 0x9c, 0xfd, 0x81, 0x93, 0xbc, 0xcd, 0xbf, 0xc1, 0x09, 0x6d, 0xf3, 0xbf, 0x97, 0xf3,
	0x2d, 0xec, 0x97, 0xcd, 0xc2, 0xf0, 0x32, 0x0f, 0xde, 0x7e, 0xf1, 0x66, 0xf7, 0x81, 0xfb, 0x64,
	0x33, 0x33, 0xae, 0x4d, 0x4e, 0x61, 0xbc, 0xb5, 0xe9, 0x3f, 0xf3, 0xc8, 0x12, 0xff, 0xeb, 0x19,
	0x8c, 0xf8, 0x17, 0x1b, 0xb4, 0x33, 0xe2, 0x9d, 0xdd, 0x11, 0x9f, 0x00, 0x48, 0x6a, 0xfb, 0xe9,
	0x63, 0xc2, 0xcb, 0xf1, 0xbf, 0xeb, 0x4c, 0x4f, 0x8a, 0x76, 0x5e, 0x92, 0xfb, 0xf2, 0x42, 0x08,
	0x48, 0x0b, 0xda, 0xbb, 0x90, 0xe4, 0x93, 0xbb, 0xb2, 0x77, 0x82, 0xf8, 0xe8, 0x57, 0x30, 0x98,
	0x5b, 0x24, 0xd3, 0x59, 0xb7, 0x9e, 0xbc, 0x7d, 0x82, 0x78, 0xa7, 0x26, 0x00, 0x77, 0xba, 0xaa,
	0x82, 0xeb, 0xb2, 0xda, 0x11, 0x11, 0x71, 0x7d, 0x0c, 0x5d, 0x19, 0xfe, 0xbe, 0xac, 0x16, 0x07,
	0x6c, 0xb3, 0x76, 0xf4, 0xa2, 0x4a, 0x32, 0x0a, 0x36, 0x33, 0x93, 0xc5, 0x98, 0x00, 0xd4, 0x58,
	0xdf, 0xd2, 0xcd, 0xda, 0x9a, 0xf7, 0xb9, 0x9b, 0x45, 0x42, 0x3e, 0xb6, 0x75, 0x92, 0xc2, 0x78,
	0xcb, 0xa4, 0x27, 0x11, 0xbf, 0xd9, 0xf1, 0x68, 0xf2, 0x5f, 0x1e, 0x6d, 0x8a, 0xc5, 0xa2, 0xdb,
	0x1e, 0xff, 0x6b, 0xfa, 0xf6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x83, 0xfb, 0x50, 0xb1,
	0x06, 0x00, 0x00,
}
