// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/game.proto

package ultimate_service_game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CrossPlayerInfo struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerId             uint32   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Gender               int32    `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Race                 int32    `protobuf:"varint,5,opt,name=race,proto3" json:"race,omitempty"`
	HeadProtrait         int32    `protobuf:"varint,6,opt,name=head_protrait,json=headProtrait,proto3" json:"head_protrait,omitempty"`
	HeadQuality          int32    `protobuf:"varint,7,opt,name=head_quality,json=headQuality,proto3" json:"head_quality,omitempty"`
	PlayerName           string   `protobuf:"bytes,8,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	GuildId              int64    `protobuf:"varint,9,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	LastLogoffTime       uint32   `protobuf:"varint,10,opt,name=last_logoff_time,json=lastLogoffTime,proto3" json:"last_logoff_time,omitempty"`
	Online               bool     `protobuf:"varint,11,opt,name=online,proto3" json:"online,omitempty"`
	Level                int32    `protobuf:"varint,12,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel             int32    `protobuf:"varint,13,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	PlayerScore          int32    `protobuf:"varint,14,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	HistoryScore         int32    `protobuf:"varint,15,opt,name=history_score,json=historyScore,proto3" json:"history_score,omitempty"`
	RemainsFloor         int32    `protobuf:"varint,16,opt,name=remains_floor,json=remainsFloor,proto3" json:"remains_floor,omitempty"`
	HeroTypeId           []uint32 `protobuf:"varint,17,rep,packed,name=hero_type_id,json=heroTypeId,proto3" json:"hero_type_id,omitempty"`
	FashionId            []uint32 `protobuf:"varint,18,rep,packed,name=fashion_id,json=fashionId,proto3" json:"fashion_id,omitempty"`
	MountTypeId          []uint32 `protobuf:"varint,19,rep,packed,name=mount_type_id,json=mountTypeId,proto3" json:"mount_type_id,omitempty"`
	RuneTypeId           []uint32 `protobuf:"varint,20,rep,packed,name=rune_type_id,json=runeTypeId,proto3" json:"rune_type_id,omitempty"`
	StateFlag            []int32  `protobuf:"varint,21,rep,packed,name=state_flag,json=stateFlag,proto3" json:"state_flag,omitempty"`
	PeakLevel            int32    `protobuf:"varint,22,opt,name=peak_level,json=peakLevel,proto3" json:"peak_level,omitempty"`
	PlayerStatus         uint32   `protobuf:"varint,23,opt,name=player_status,json=playerStatus,proto3" json:"player_status,omitempty"`
	CurDecorate          int32    `protobuf:"varint,24,opt,name=cur_decorate,json=curDecorate,proto3" json:"cur_decorate,omitempty"`
	ReturnPlayerId       int64    `protobuf:"varint,25,opt,name=return_player_id,json=returnPlayerId,proto3" json:"return_player_id,omitempty"`
	LastSquareActionTime uint32   `protobuf:"varint,26,opt,name=last_square_action_time,json=lastSquareActionTime,proto3" json:"last_square_action_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossPlayerInfo) Reset()         { *m = CrossPlayerInfo{} }
func (m *CrossPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CrossPlayerInfo) ProtoMessage()    {}
func (*CrossPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{0}
}

func (m *CrossPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossPlayerInfo.Unmarshal(m, b)
}
func (m *CrossPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossPlayerInfo.Marshal(b, m, deterministic)
}
func (m *CrossPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossPlayerInfo.Merge(m, src)
}
func (m *CrossPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CrossPlayerInfo.Size(m)
}
func (m *CrossPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CrossPlayerInfo proto.InternalMessageInfo

func (m *CrossPlayerInfo) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *CrossPlayerInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CrossPlayerInfo) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *CrossPlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *CrossPlayerInfo) GetRace() int32 {
	if m != nil {
		return m.Race
	}
	return 0
}

func (m *CrossPlayerInfo) GetHeadProtrait() int32 {
	if m != nil {
		return m.HeadProtrait
	}
	return 0
}

func (m *CrossPlayerInfo) GetHeadQuality() int32 {
	if m != nil {
		return m.HeadQuality
	}
	return 0
}

func (m *CrossPlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *CrossPlayerInfo) GetGuildId() int64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *CrossPlayerInfo) GetLastLogoffTime() uint32 {
	if m != nil {
		return m.LastLogoffTime
	}
	return 0
}

func (m *CrossPlayerInfo) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *CrossPlayerInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *CrossPlayerInfo) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *CrossPlayerInfo) GetPlayerScore() int32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *CrossPlayerInfo) GetHistoryScore() int32 {
	if m != nil {
		return m.HistoryScore
	}
	return 0
}

func (m *CrossPlayerInfo) GetRemainsFloor() int32 {
	if m != nil {
		return m.RemainsFloor
	}
	return 0
}

func (m *CrossPlayerInfo) GetHeroTypeId() []uint32 {
	if m != nil {
		return m.HeroTypeId
	}
	return nil
}

func (m *CrossPlayerInfo) GetFashionId() []uint32 {
	if m != nil {
		return m.FashionId
	}
	return nil
}

func (m *CrossPlayerInfo) GetMountTypeId() []uint32 {
	if m != nil {
		return m.MountTypeId
	}
	return nil
}

func (m *CrossPlayerInfo) GetRuneTypeId() []uint32 {
	if m != nil {
		return m.RuneTypeId
	}
	return nil
}

func (m *CrossPlayerInfo) GetStateFlag() []int32 {
	if m != nil {
		return m.StateFlag
	}
	return nil
}

func (m *CrossPlayerInfo) GetPeakLevel() int32 {
	if m != nil {
		return m.PeakLevel
	}
	return 0
}

func (m *CrossPlayerInfo) GetPlayerStatus() uint32 {
	if m != nil {
		return m.PlayerStatus
	}
	return 0
}

func (m *CrossPlayerInfo) GetCurDecorate() int32 {
	if m != nil {
		return m.CurDecorate
	}
	return 0
}

func (m *CrossPlayerInfo) GetReturnPlayerId() int64 {
	if m != nil {
		return m.ReturnPlayerId
	}
	return 0
}

func (m *CrossPlayerInfo) GetLastSquareActionTime() uint32 {
	if m != nil {
		return m.LastSquareActionTime
	}
	return 0
}

type CrossGuildInfo struct {
	GuildId              int64    `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GuildName            string   `protobuf:"bytes,2,opt,name=guild_name,json=guildName,proto3" json:"guild_name,omitempty"`
	ServerId             uint32   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MasterId             int64    `protobuf:"varint,4,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	MasterName           string   `protobuf:"bytes,5,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	CreateTime           uint32   `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	HallLevel            int32    `protobuf:"varint,7,opt,name=hall_level,json=hallLevel,proto3" json:"hall_level,omitempty"`
	Score                int32    `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	CastleScore          int32    `protobuf:"varint,9,opt,name=castle_score,json=castleScore,proto3" json:"castle_score,omitempty"`
	MemberNum            int32    `protobuf:"varint,10,opt,name=member_num,json=memberNum,proto3" json:"member_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossGuildInfo) Reset()         { *m = CrossGuildInfo{} }
func (m *CrossGuildInfo) String() string { return proto.CompactTextString(m) }
func (*CrossGuildInfo) ProtoMessage()    {}
func (*CrossGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{1}
}

func (m *CrossGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossGuildInfo.Unmarshal(m, b)
}
func (m *CrossGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossGuildInfo.Marshal(b, m, deterministic)
}
func (m *CrossGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossGuildInfo.Merge(m, src)
}
func (m *CrossGuildInfo) XXX_Size() int {
	return xxx_messageInfo_CrossGuildInfo.Size(m)
}
func (m *CrossGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CrossGuildInfo proto.InternalMessageInfo

func (m *CrossGuildInfo) GetGuildId() int64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *CrossGuildInfo) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *CrossGuildInfo) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *CrossGuildInfo) GetMasterId() int64 {
	if m != nil {
		return m.MasterId
	}
	return 0
}

func (m *CrossGuildInfo) GetMasterName() string {
	if m != nil {
		return m.MasterName
	}
	return ""
}

func (m *CrossGuildInfo) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *CrossGuildInfo) GetHallLevel() int32 {
	if m != nil {
		return m.HallLevel
	}
	return 0
}

func (m *CrossGuildInfo) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *CrossGuildInfo) GetCastleScore() int32 {
	if m != nil {
		return m.CastleScore
	}
	return 0
}

func (m *CrossGuildInfo) GetMemberNum() int32 {
	if m != nil {
		return m.MemberNum
	}
	return 0
}

type MWU_RequestPlayerInfo struct {
	Info                 []*CrossPlayerInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MWU_RequestPlayerInfo) Reset()         { *m = MWU_RequestPlayerInfo{} }
func (m *MWU_RequestPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MWU_RequestPlayerInfo) ProtoMessage()    {}
func (*MWU_RequestPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{2}
}

func (m *MWU_RequestPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_RequestPlayerInfo.Unmarshal(m, b)
}
func (m *MWU_RequestPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_RequestPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MWU_RequestPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_RequestPlayerInfo.Merge(m, src)
}
func (m *MWU_RequestPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MWU_RequestPlayerInfo.Size(m)
}
func (m *MWU_RequestPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_RequestPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_RequestPlayerInfo proto.InternalMessageInfo

func (m *MWU_RequestPlayerInfo) GetInfo() []*CrossPlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MWU_ReplacePlayerInfo struct {
	Info                 *CrossPlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MWU_ReplacePlayerInfo) Reset()         { *m = MWU_ReplacePlayerInfo{} }
func (m *MWU_ReplacePlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MWU_ReplacePlayerInfo) ProtoMessage()    {}
func (*MWU_ReplacePlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{3}
}

func (m *MWU_ReplacePlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_ReplacePlayerInfo.Unmarshal(m, b)
}
func (m *MWU_ReplacePlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_ReplacePlayerInfo.Marshal(b, m, deterministic)
}
func (m *MWU_ReplacePlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_ReplacePlayerInfo.Merge(m, src)
}
func (m *MWU_ReplacePlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MWU_ReplacePlayerInfo.Size(m)
}
func (m *MWU_ReplacePlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_ReplacePlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_ReplacePlayerInfo proto.InternalMessageInfo

func (m *MWU_ReplacePlayerInfo) GetInfo() *CrossPlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MWU_RequestGuildInfo struct {
	Info                 []*CrossGuildInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MWU_RequestGuildInfo) Reset()         { *m = MWU_RequestGuildInfo{} }
func (m *MWU_RequestGuildInfo) String() string { return proto.CompactTextString(m) }
func (*MWU_RequestGuildInfo) ProtoMessage()    {}
func (*MWU_RequestGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{4}
}

func (m *MWU_RequestGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_RequestGuildInfo.Unmarshal(m, b)
}
func (m *MWU_RequestGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_RequestGuildInfo.Marshal(b, m, deterministic)
}
func (m *MWU_RequestGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_RequestGuildInfo.Merge(m, src)
}
func (m *MWU_RequestGuildInfo) XXX_Size() int {
	return xxx_messageInfo_MWU_RequestGuildInfo.Size(m)
}
func (m *MWU_RequestGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_RequestGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_RequestGuildInfo proto.InternalMessageInfo

func (m *MWU_RequestGuildInfo) GetInfo() []*CrossGuildInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MWU_ReplaceGuildInfo struct {
	Info                 *CrossGuildInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MWU_ReplaceGuildInfo) Reset()         { *m = MWU_ReplaceGuildInfo{} }
func (m *MWU_ReplaceGuildInfo) String() string { return proto.CompactTextString(m) }
func (*MWU_ReplaceGuildInfo) ProtoMessage()    {}
func (*MWU_ReplaceGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{5}
}

func (m *MWU_ReplaceGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_ReplaceGuildInfo.Unmarshal(m, b)
}
func (m *MWU_ReplaceGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_ReplaceGuildInfo.Marshal(b, m, deterministic)
}
func (m *MWU_ReplaceGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_ReplaceGuildInfo.Merge(m, src)
}
func (m *MWU_ReplaceGuildInfo) XXX_Size() int {
	return xxx_messageInfo_MWU_ReplaceGuildInfo.Size(m)
}
func (m *MWU_ReplaceGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_ReplaceGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_ReplaceGuildInfo proto.InternalMessageInfo

func (m *MWU_ReplaceGuildInfo) GetInfo() *CrossGuildInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MUW_RequestPlayerInfo struct {
	MinLevel             int32    `protobuf:"varint,1,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestPlayerInfo) Reset()         { *m = MUW_RequestPlayerInfo{} }
func (m *MUW_RequestPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestPlayerInfo) ProtoMessage()    {}
func (*MUW_RequestPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{6}
}

func (m *MUW_RequestPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Unmarshal(m, b)
}
func (m *MUW_RequestPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MUW_RequestPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestPlayerInfo.Merge(m, src)
}
func (m *MUW_RequestPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestPlayerInfo.Size(m)
}
func (m *MUW_RequestPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestPlayerInfo proto.InternalMessageInfo

func (m *MUW_RequestPlayerInfo) GetMinLevel() int32 {
	if m != nil {
		return m.MinLevel
	}
	return 0
}

type MUW_RequestGuildInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestGuildInfo) Reset()         { *m = MUW_RequestGuildInfo{} }
func (m *MUW_RequestGuildInfo) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestGuildInfo) ProtoMessage()    {}
func (*MUW_RequestGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{7}
}

func (m *MUW_RequestGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestGuildInfo.Unmarshal(m, b)
}
func (m *MUW_RequestGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestGuildInfo.Marshal(b, m, deterministic)
}
func (m *MUW_RequestGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestGuildInfo.Merge(m, src)
}
func (m *MUW_RequestGuildInfo) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestGuildInfo.Size(m)
}
func (m *MUW_RequestGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestGuildInfo proto.InternalMessageInfo

type MWU_PlayUltimateRecord struct {
	SrcPlayerId          int64    `protobuf:"varint,1,opt,name=src_player_id,json=srcPlayerId,proto3" json:"src_player_id,omitempty"`
	SrcServerId          uint32   `protobuf:"varint,2,opt,name=src_server_id,json=srcServerId,proto3" json:"src_server_id,omitempty"`
	RecordId             int64    `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	DstServerId          uint32   `protobuf:"varint,4,opt,name=dst_server_id,json=dstServerId,proto3" json:"dst_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_PlayUltimateRecord) Reset()         { *m = MWU_PlayUltimateRecord{} }
func (m *MWU_PlayUltimateRecord) String() string { return proto.CompactTextString(m) }
func (*MWU_PlayUltimateRecord) ProtoMessage()    {}
func (*MWU_PlayUltimateRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{8}
}

func (m *MWU_PlayUltimateRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_PlayUltimateRecord.Unmarshal(m, b)
}
func (m *MWU_PlayUltimateRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_PlayUltimateRecord.Marshal(b, m, deterministic)
}
func (m *MWU_PlayUltimateRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_PlayUltimateRecord.Merge(m, src)
}
func (m *MWU_PlayUltimateRecord) XXX_Size() int {
	return xxx_messageInfo_MWU_PlayUltimateRecord.Size(m)
}
func (m *MWU_PlayUltimateRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_PlayUltimateRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_PlayUltimateRecord proto.InternalMessageInfo

func (m *MWU_PlayUltimateRecord) GetSrcPlayerId() int64 {
	if m != nil {
		return m.SrcPlayerId
	}
	return 0
}

func (m *MWU_PlayUltimateRecord) GetSrcServerId() uint32 {
	if m != nil {
		return m.SrcServerId
	}
	return 0
}

func (m *MWU_PlayUltimateRecord) GetRecordId() int64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *MWU_PlayUltimateRecord) GetDstServerId() uint32 {
	if m != nil {
		return m.DstServerId
	}
	return 0
}

type MUW_PlayUltimateRecord struct {
	SrcPlayerId          int64    `protobuf:"varint,1,opt,name=src_player_id,json=srcPlayerId,proto3" json:"src_player_id,omitempty"`
	SrcServerId          uint32   `protobuf:"varint,2,opt,name=src_server_id,json=srcServerId,proto3" json:"src_server_id,omitempty"`
	RecordId             int64    `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	DstServerId          uint32   `protobuf:"varint,4,opt,name=dst_server_id,json=dstServerId,proto3" json:"dst_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_PlayUltimateRecord) Reset()         { *m = MUW_PlayUltimateRecord{} }
func (m *MUW_PlayUltimateRecord) String() string { return proto.CompactTextString(m) }
func (*MUW_PlayUltimateRecord) ProtoMessage()    {}
func (*MUW_PlayUltimateRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{9}
}

func (m *MUW_PlayUltimateRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_PlayUltimateRecord.Unmarshal(m, b)
}
func (m *MUW_PlayUltimateRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_PlayUltimateRecord.Marshal(b, m, deterministic)
}
func (m *MUW_PlayUltimateRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_PlayUltimateRecord.Merge(m, src)
}
func (m *MUW_PlayUltimateRecord) XXX_Size() int {
	return xxx_messageInfo_MUW_PlayUltimateRecord.Size(m)
}
func (m *MUW_PlayUltimateRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_PlayUltimateRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_PlayUltimateRecord proto.InternalMessageInfo

func (m *MUW_PlayUltimateRecord) GetSrcPlayerId() int64 {
	if m != nil {
		return m.SrcPlayerId
	}
	return 0
}

func (m *MUW_PlayUltimateRecord) GetSrcServerId() uint32 {
	if m != nil {
		return m.SrcServerId
	}
	return 0
}

func (m *MUW_PlayUltimateRecord) GetRecordId() int64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *MUW_PlayUltimateRecord) GetDstServerId() uint32 {
	if m != nil {
		return m.DstServerId
	}
	return 0
}

type MWU_RequestUltimatePlayer struct {
	SrcPlayerId          int64    `protobuf:"varint,1,opt,name=src_player_id,json=srcPlayerId,proto3" json:"src_player_id,omitempty"`
	SrcServerId          uint32   `protobuf:"varint,2,opt,name=src_server_id,json=srcServerId,proto3" json:"src_server_id,omitempty"`
	DstPlayerId          int64    `protobuf:"varint,3,opt,name=dst_player_id,json=dstPlayerId,proto3" json:"dst_player_id,omitempty"`
	DstServerId          uint32   `protobuf:"varint,4,opt,name=dst_server_id,json=dstServerId,proto3" json:"dst_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_RequestUltimatePlayer) Reset()         { *m = MWU_RequestUltimatePlayer{} }
func (m *MWU_RequestUltimatePlayer) String() string { return proto.CompactTextString(m) }
func (*MWU_RequestUltimatePlayer) ProtoMessage()    {}
func (*MWU_RequestUltimatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{10}
}

func (m *MWU_RequestUltimatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_RequestUltimatePlayer.Unmarshal(m, b)
}
func (m *MWU_RequestUltimatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_RequestUltimatePlayer.Marshal(b, m, deterministic)
}
func (m *MWU_RequestUltimatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_RequestUltimatePlayer.Merge(m, src)
}
func (m *MWU_RequestUltimatePlayer) XXX_Size() int {
	return xxx_messageInfo_MWU_RequestUltimatePlayer.Size(m)
}
func (m *MWU_RequestUltimatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_RequestUltimatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_RequestUltimatePlayer proto.InternalMessageInfo

func (m *MWU_RequestUltimatePlayer) GetSrcPlayerId() int64 {
	if m != nil {
		return m.SrcPlayerId
	}
	return 0
}

func (m *MWU_RequestUltimatePlayer) GetSrcServerId() uint32 {
	if m != nil {
		return m.SrcServerId
	}
	return 0
}

func (m *MWU_RequestUltimatePlayer) GetDstPlayerId() int64 {
	if m != nil {
		return m.DstPlayerId
	}
	return 0
}

func (m *MWU_RequestUltimatePlayer) GetDstServerId() uint32 {
	if m != nil {
		return m.DstServerId
	}
	return 0
}

type MUW_RequestUltimatePlayer struct {
	SrcPlayerId          int64    `protobuf:"varint,1,opt,name=src_player_id,json=srcPlayerId,proto3" json:"src_player_id,omitempty"`
	SrcServerId          uint32   `protobuf:"varint,2,opt,name=src_server_id,json=srcServerId,proto3" json:"src_server_id,omitempty"`
	DstPlayerId          int64    `protobuf:"varint,3,opt,name=dst_player_id,json=dstPlayerId,proto3" json:"dst_player_id,omitempty"`
	DstServerId          uint32   `protobuf:"varint,4,opt,name=dst_server_id,json=dstServerId,proto3" json:"dst_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_RequestUltimatePlayer) Reset()         { *m = MUW_RequestUltimatePlayer{} }
func (m *MUW_RequestUltimatePlayer) String() string { return proto.CompactTextString(m) }
func (*MUW_RequestUltimatePlayer) ProtoMessage()    {}
func (*MUW_RequestUltimatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{11}
}

func (m *MUW_RequestUltimatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_RequestUltimatePlayer.Unmarshal(m, b)
}
func (m *MUW_RequestUltimatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_RequestUltimatePlayer.Marshal(b, m, deterministic)
}
func (m *MUW_RequestUltimatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_RequestUltimatePlayer.Merge(m, src)
}
func (m *MUW_RequestUltimatePlayer) XXX_Size() int {
	return xxx_messageInfo_MUW_RequestUltimatePlayer.Size(m)
}
func (m *MUW_RequestUltimatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_RequestUltimatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_RequestUltimatePlayer proto.InternalMessageInfo

func (m *MUW_RequestUltimatePlayer) GetSrcPlayerId() int64 {
	if m != nil {
		return m.SrcPlayerId
	}
	return 0
}

func (m *MUW_RequestUltimatePlayer) GetSrcServerId() uint32 {
	if m != nil {
		return m.SrcServerId
	}
	return 0
}

func (m *MUW_RequestUltimatePlayer) GetDstPlayerId() int64 {
	if m != nil {
		return m.DstPlayerId
	}
	return 0
}

func (m *MUW_RequestUltimatePlayer) GetDstServerId() uint32 {
	if m != nil {
		return m.DstServerId
	}
	return 0
}

type MWU_ViewFormation struct {
	SrcPlayerId          int64    `protobuf:"varint,1,opt,name=src_player_id,json=srcPlayerId,proto3" json:"src_player_id,omitempty"`
	SrcServerId          uint32   `protobuf:"varint,2,opt,name=src_server_id,json=srcServerId,proto3" json:"src_server_id,omitempty"`
	DstPlayerId          int64    `protobuf:"varint,3,opt,name=dst_player_id,json=dstPlayerId,proto3" json:"dst_player_id,omitempty"`
	DstServerId          uint32   `protobuf:"varint,4,opt,name=dst_server_id,json=dstServerId,proto3" json:"dst_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_ViewFormation) Reset()         { *m = MWU_ViewFormation{} }
func (m *MWU_ViewFormation) String() string { return proto.CompactTextString(m) }
func (*MWU_ViewFormation) ProtoMessage()    {}
func (*MWU_ViewFormation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{12}
}

func (m *MWU_ViewFormation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_ViewFormation.Unmarshal(m, b)
}
func (m *MWU_ViewFormation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_ViewFormation.Marshal(b, m, deterministic)
}
func (m *MWU_ViewFormation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_ViewFormation.Merge(m, src)
}
func (m *MWU_ViewFormation) XXX_Size() int {
	return xxx_messageInfo_MWU_ViewFormation.Size(m)
}
func (m *MWU_ViewFormation) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_ViewFormation.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_ViewFormation proto.InternalMessageInfo

func (m *MWU_ViewFormation) GetSrcPlayerId() int64 {
	if m != nil {
		return m.SrcPlayerId
	}
	return 0
}

func (m *MWU_ViewFormation) GetSrcServerId() uint32 {
	if m != nil {
		return m.SrcServerId
	}
	return 0
}

func (m *MWU_ViewFormation) GetDstPlayerId() int64 {
	if m != nil {
		return m.DstPlayerId
	}
	return 0
}

func (m *MWU_ViewFormation) GetDstServerId() uint32 {
	if m != nil {
		return m.DstServerId
	}
	return 0
}

type MUW_ViewFormation struct {
	SrcPlayerId          int64    `protobuf:"varint,1,opt,name=src_player_id,json=srcPlayerId,proto3" json:"src_player_id,omitempty"`
	SrcServerId          uint32   `protobuf:"varint,2,opt,name=src_server_id,json=srcServerId,proto3" json:"src_server_id,omitempty"`
	DstPlayerId          int64    `protobuf:"varint,3,opt,name=dst_player_id,json=dstPlayerId,proto3" json:"dst_player_id,omitempty"`
	DstServerId          uint32   `protobuf:"varint,4,opt,name=dst_server_id,json=dstServerId,proto3" json:"dst_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_ViewFormation) Reset()         { *m = MUW_ViewFormation{} }
func (m *MUW_ViewFormation) String() string { return proto.CompactTextString(m) }
func (*MUW_ViewFormation) ProtoMessage()    {}
func (*MUW_ViewFormation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{13}
}

func (m *MUW_ViewFormation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_ViewFormation.Unmarshal(m, b)
}
func (m *MUW_ViewFormation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_ViewFormation.Marshal(b, m, deterministic)
}
func (m *MUW_ViewFormation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_ViewFormation.Merge(m, src)
}
func (m *MUW_ViewFormation) XXX_Size() int {
	return xxx_messageInfo_MUW_ViewFormation.Size(m)
}
func (m *MUW_ViewFormation) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_ViewFormation.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_ViewFormation proto.InternalMessageInfo

func (m *MUW_ViewFormation) GetSrcPlayerId() int64 {
	if m != nil {
		return m.SrcPlayerId
	}
	return 0
}

func (m *MUW_ViewFormation) GetSrcServerId() uint32 {
	if m != nil {
		return m.SrcServerId
	}
	return 0
}

func (m *MUW_ViewFormation) GetDstPlayerId() int64 {
	if m != nil {
		return m.DstPlayerId
	}
	return 0
}

func (m *MUW_ViewFormation) GetDstServerId() uint32 {
	if m != nil {
		return m.DstServerId
	}
	return 0
}

type MUW_CheckInvite struct {
	NewbieId             int64    `protobuf:"varint,1,opt,name=newbie_id,json=newbieId,proto3" json:"newbie_id,omitempty"`
	InviterId            int64    `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_CheckInvite) Reset()         { *m = MUW_CheckInvite{} }
func (m *MUW_CheckInvite) String() string { return proto.CompactTextString(m) }
func (*MUW_CheckInvite) ProtoMessage()    {}
func (*MUW_CheckInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{14}
}

func (m *MUW_CheckInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_CheckInvite.Unmarshal(m, b)
}
func (m *MUW_CheckInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_CheckInvite.Marshal(b, m, deterministic)
}
func (m *MUW_CheckInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_CheckInvite.Merge(m, src)
}
func (m *MUW_CheckInvite) XXX_Size() int {
	return xxx_messageInfo_MUW_CheckInvite.Size(m)
}
func (m *MUW_CheckInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_CheckInvite.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_CheckInvite proto.InternalMessageInfo

func (m *MUW_CheckInvite) GetNewbieId() int64 {
	if m != nil {
		return m.NewbieId
	}
	return 0
}

func (m *MUW_CheckInvite) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

type MWU_CheckInviteResult struct {
	NewbieId             int64    `protobuf:"varint,1,opt,name=newbie_id,json=newbieId,proto3" json:"newbie_id,omitempty"`
	InviterId            int64    `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_CheckInviteResult) Reset()         { *m = MWU_CheckInviteResult{} }
func (m *MWU_CheckInviteResult) String() string { return proto.CompactTextString(m) }
func (*MWU_CheckInviteResult) ProtoMessage()    {}
func (*MWU_CheckInviteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{15}
}

func (m *MWU_CheckInviteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_CheckInviteResult.Unmarshal(m, b)
}
func (m *MWU_CheckInviteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_CheckInviteResult.Marshal(b, m, deterministic)
}
func (m *MWU_CheckInviteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_CheckInviteResult.Merge(m, src)
}
func (m *MWU_CheckInviteResult) XXX_Size() int {
	return xxx_messageInfo_MWU_CheckInviteResult.Size(m)
}
func (m *MWU_CheckInviteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_CheckInviteResult.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_CheckInviteResult proto.InternalMessageInfo

func (m *MWU_CheckInviteResult) GetNewbieId() int64 {
	if m != nil {
		return m.NewbieId
	}
	return 0
}

func (m *MWU_CheckInviteResult) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

func (m *MWU_CheckInviteResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MWU_AddInvite struct {
	NewbieId             int64    `protobuf:"varint,1,opt,name=newbie_id,json=newbieId,proto3" json:"newbie_id,omitempty"`
	InviterId            int64    `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_AddInvite) Reset()         { *m = MWU_AddInvite{} }
func (m *MWU_AddInvite) String() string { return proto.CompactTextString(m) }
func (*MWU_AddInvite) ProtoMessage()    {}
func (*MWU_AddInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{16}
}

func (m *MWU_AddInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_AddInvite.Unmarshal(m, b)
}
func (m *MWU_AddInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_AddInvite.Marshal(b, m, deterministic)
}
func (m *MWU_AddInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_AddInvite.Merge(m, src)
}
func (m *MWU_AddInvite) XXX_Size() int {
	return xxx_messageInfo_MWU_AddInvite.Size(m)
}
func (m *MWU_AddInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_AddInvite.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_AddInvite proto.InternalMessageInfo

func (m *MWU_AddInvite) GetNewbieId() int64 {
	if m != nil {
		return m.NewbieId
	}
	return 0
}

func (m *MWU_AddInvite) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

type MUW_AddInviteResult struct {
	NewbieId             int64    `protobuf:"varint,1,opt,name=newbie_id,json=newbieId,proto3" json:"newbie_id,omitempty"`
	InviterId            int64    `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_AddInviteResult) Reset()         { *m = MUW_AddInviteResult{} }
func (m *MUW_AddInviteResult) String() string { return proto.CompactTextString(m) }
func (*MUW_AddInviteResult) ProtoMessage()    {}
func (*MUW_AddInviteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{17}
}

func (m *MUW_AddInviteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_AddInviteResult.Unmarshal(m, b)
}
func (m *MUW_AddInviteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_AddInviteResult.Marshal(b, m, deterministic)
}
func (m *MUW_AddInviteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_AddInviteResult.Merge(m, src)
}
func (m *MUW_AddInviteResult) XXX_Size() int {
	return xxx_messageInfo_MUW_AddInviteResult.Size(m)
}
func (m *MUW_AddInviteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_AddInviteResult.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_AddInviteResult proto.InternalMessageInfo

func (m *MUW_AddInviteResult) GetNewbieId() int64 {
	if m != nil {
		return m.NewbieId
	}
	return 0
}

func (m *MUW_AddInviteResult) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

func (m *MUW_AddInviteResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MWU_InviteRecharge struct {
	NewbieId             int64    `protobuf:"varint,1,opt,name=newbie_id,json=newbieId,proto3" json:"newbie_id,omitempty"`
	NewbieName           string   `protobuf:"bytes,2,opt,name=newbie_name,json=newbieName,proto3" json:"newbie_name,omitempty"`
	InviterId            int64    `protobuf:"varint,3,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	DiamondGift          int32    `protobuf:"varint,4,opt,name=diamond_gift,json=diamondGift,proto3" json:"diamond_gift,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MWU_InviteRecharge) Reset()         { *m = MWU_InviteRecharge{} }
func (m *MWU_InviteRecharge) String() string { return proto.CompactTextString(m) }
func (*MWU_InviteRecharge) ProtoMessage()    {}
func (*MWU_InviteRecharge) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{18}
}

func (m *MWU_InviteRecharge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MWU_InviteRecharge.Unmarshal(m, b)
}
func (m *MWU_InviteRecharge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MWU_InviteRecharge.Marshal(b, m, deterministic)
}
func (m *MWU_InviteRecharge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MWU_InviteRecharge.Merge(m, src)
}
func (m *MWU_InviteRecharge) XXX_Size() int {
	return xxx_messageInfo_MWU_InviteRecharge.Size(m)
}
func (m *MWU_InviteRecharge) XXX_DiscardUnknown() {
	xxx_messageInfo_MWU_InviteRecharge.DiscardUnknown(m)
}

var xxx_messageInfo_MWU_InviteRecharge proto.InternalMessageInfo

func (m *MWU_InviteRecharge) GetNewbieId() int64 {
	if m != nil {
		return m.NewbieId
	}
	return 0
}

func (m *MWU_InviteRecharge) GetNewbieName() string {
	if m != nil {
		return m.NewbieName
	}
	return ""
}

func (m *MWU_InviteRecharge) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

func (m *MWU_InviteRecharge) GetDiamondGift() int32 {
	if m != nil {
		return m.DiamondGift
	}
	return 0
}

type MUW_InviteRecharge struct {
	NewbieId             int64    `protobuf:"varint,1,opt,name=newbie_id,json=newbieId,proto3" json:"newbie_id,omitempty"`
	NewbieName           string   `protobuf:"bytes,2,opt,name=newbie_name,json=newbieName,proto3" json:"newbie_name,omitempty"`
	InviterId            int64    `protobuf:"varint,3,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	DiamondGift          int32    `protobuf:"varint,4,opt,name=diamond_gift,json=diamondGift,proto3" json:"diamond_gift,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MUW_InviteRecharge) Reset()         { *m = MUW_InviteRecharge{} }
func (m *MUW_InviteRecharge) String() string { return proto.CompactTextString(m) }
func (*MUW_InviteRecharge) ProtoMessage()    {}
func (*MUW_InviteRecharge) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{19}
}

func (m *MUW_InviteRecharge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MUW_InviteRecharge.Unmarshal(m, b)
}
func (m *MUW_InviteRecharge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MUW_InviteRecharge.Marshal(b, m, deterministic)
}
func (m *MUW_InviteRecharge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MUW_InviteRecharge.Merge(m, src)
}
func (m *MUW_InviteRecharge) XXX_Size() int {
	return xxx_messageInfo_MUW_InviteRecharge.Size(m)
}
func (m *MUW_InviteRecharge) XXX_DiscardUnknown() {
	xxx_messageInfo_MUW_InviteRecharge.DiscardUnknown(m)
}

var xxx_messageInfo_MUW_InviteRecharge proto.InternalMessageInfo

func (m *MUW_InviteRecharge) GetNewbieId() int64 {
	if m != nil {
		return m.NewbieId
	}
	return 0
}

func (m *MUW_InviteRecharge) GetNewbieName() string {
	if m != nil {
		return m.NewbieName
	}
	return ""
}

func (m *MUW_InviteRecharge) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

func (m *MUW_InviteRecharge) GetDiamondGift() int32 {
	if m != nil {
		return m.DiamondGift
	}
	return 0
}

type GetPlayerInfoByIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerInfoByIDRequest) Reset()         { *m = GetPlayerInfoByIDRequest{} }
func (m *GetPlayerInfoByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerInfoByIDRequest) ProtoMessage()    {}
func (*GetPlayerInfoByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{20}
}

func (m *GetPlayerInfoByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerInfoByIDRequest.Unmarshal(m, b)
}
func (m *GetPlayerInfoByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerInfoByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerInfoByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerInfoByIDRequest.Merge(m, src)
}
func (m *GetPlayerInfoByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerInfoByIDRequest.Size(m)
}
func (m *GetPlayerInfoByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerInfoByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerInfoByIDRequest proto.InternalMessageInfo

func (m *GetPlayerInfoByIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPlayerInfoByIDReply struct {
	Info                 *CrossPlayerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetPlayerInfoByIDReply) Reset()         { *m = GetPlayerInfoByIDReply{} }
func (m *GetPlayerInfoByIDReply) String() string { return proto.CompactTextString(m) }
func (*GetPlayerInfoByIDReply) ProtoMessage()    {}
func (*GetPlayerInfoByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{21}
}

func (m *GetPlayerInfoByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerInfoByIDReply.Unmarshal(m, b)
}
func (m *GetPlayerInfoByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerInfoByIDReply.Marshal(b, m, deterministic)
}
func (m *GetPlayerInfoByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerInfoByIDReply.Merge(m, src)
}
func (m *GetPlayerInfoByIDReply) XXX_Size() int {
	return xxx_messageInfo_GetPlayerInfoByIDReply.Size(m)
}
func (m *GetPlayerInfoByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerInfoByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerInfoByIDReply proto.InternalMessageInfo

func (m *GetPlayerInfoByIDReply) GetInfo() *CrossPlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetGuildInfoByIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGuildInfoByIDRequest) Reset()         { *m = GetGuildInfoByIDRequest{} }
func (m *GetGuildInfoByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetGuildInfoByIDRequest) ProtoMessage()    {}
func (*GetGuildInfoByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{22}
}

func (m *GetGuildInfoByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGuildInfoByIDRequest.Unmarshal(m, b)
}
func (m *GetGuildInfoByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGuildInfoByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetGuildInfoByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGuildInfoByIDRequest.Merge(m, src)
}
func (m *GetGuildInfoByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetGuildInfoByIDRequest.Size(m)
}
func (m *GetGuildInfoByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGuildInfoByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGuildInfoByIDRequest proto.InternalMessageInfo

func (m *GetGuildInfoByIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGuildInfoByIDReply struct {
	Info                 *CrossGuildInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetGuildInfoByIDReply) Reset()         { *m = GetGuildInfoByIDReply{} }
func (m *GetGuildInfoByIDReply) String() string { return proto.CompactTextString(m) }
func (*GetGuildInfoByIDReply) ProtoMessage()    {}
func (*GetGuildInfoByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{23}
}

func (m *GetGuildInfoByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGuildInfoByIDReply.Unmarshal(m, b)
}
func (m *GetGuildInfoByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGuildInfoByIDReply.Marshal(b, m, deterministic)
}
func (m *GetGuildInfoByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGuildInfoByIDReply.Merge(m, src)
}
func (m *GetGuildInfoByIDReply) XXX_Size() int {
	return xxx_messageInfo_GetGuildInfoByIDReply.Size(m)
}
func (m *GetGuildInfoByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGuildInfoByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGuildInfoByIDReply proto.InternalMessageInfo

func (m *GetGuildInfoByIDReply) GetInfo() *CrossGuildInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

/////////////////////////////////////////////////
// pub/sub
/////////////////////////////////////////////////
type PublishBroadCast struct {
	MsgName              string   `protobuf:"bytes,1,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishBroadCast) Reset()         { *m = PublishBroadCast{} }
func (m *PublishBroadCast) String() string { return proto.CompactTextString(m) }
func (*PublishBroadCast) ProtoMessage()    {}
func (*PublishBroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{24}
}

func (m *PublishBroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishBroadCast.Unmarshal(m, b)
}
func (m *PublishBroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishBroadCast.Marshal(b, m, deterministic)
}
func (m *PublishBroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishBroadCast.Merge(m, src)
}
func (m *PublishBroadCast) XXX_Size() int {
	return xxx_messageInfo_PublishBroadCast.Size(m)
}
func (m *PublishBroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishBroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_PublishBroadCast proto.InternalMessageInfo

func (m *PublishBroadCast) GetMsgName() string {
	if m != nil {
		return m.MsgName
	}
	return ""
}

func (m *PublishBroadCast) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

type PublishSendWorldMessage struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgName              string   `protobuf:"bytes,2,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	MsgData              []byte   `protobuf:"bytes,3,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishSendWorldMessage) Reset()         { *m = PublishSendWorldMessage{} }
func (m *PublishSendWorldMessage) String() string { return proto.CompactTextString(m) }
func (*PublishSendWorldMessage) ProtoMessage()    {}
func (*PublishSendWorldMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{25}
}

func (m *PublishSendWorldMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishSendWorldMessage.Unmarshal(m, b)
}
func (m *PublishSendWorldMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishSendWorldMessage.Marshal(b, m, deterministic)
}
func (m *PublishSendWorldMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishSendWorldMessage.Merge(m, src)
}
func (m *PublishSendWorldMessage) XXX_Size() int {
	return xxx_messageInfo_PublishSendWorldMessage.Size(m)
}
func (m *PublishSendWorldMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishSendWorldMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PublishSendWorldMessage proto.InternalMessageInfo

func (m *PublishSendWorldMessage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PublishSendWorldMessage) GetMsgName() string {
	if m != nil {
		return m.MsgName
	}
	return ""
}

func (m *PublishSendWorldMessage) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func init() {
	proto.RegisterType((*CrossPlayerInfo)(nil), "ultimate.service.game.CrossPlayerInfo")
	proto.RegisterType((*CrossGuildInfo)(nil), "ultimate.service.game.CrossGuildInfo")
	proto.RegisterType((*MWU_RequestPlayerInfo)(nil), "ultimate.service.game.MWU_RequestPlayerInfo")
	proto.RegisterType((*MWU_ReplacePlayerInfo)(nil), "ultimate.service.game.MWU_ReplacePlayerInfo")
	proto.RegisterType((*MWU_RequestGuildInfo)(nil), "ultimate.service.game.MWU_RequestGuildInfo")
	proto.RegisterType((*MWU_ReplaceGuildInfo)(nil), "ultimate.service.game.MWU_ReplaceGuildInfo")
	proto.RegisterType((*MUW_RequestPlayerInfo)(nil), "ultimate.service.game.MUW_RequestPlayerInfo")
	proto.RegisterType((*MUW_RequestGuildInfo)(nil), "ultimate.service.game.MUW_RequestGuildInfo")
	proto.RegisterType((*MWU_PlayUltimateRecord)(nil), "ultimate.service.game.MWU_PlayUltimateRecord")
	proto.RegisterType((*MUW_PlayUltimateRecord)(nil), "ultimate.service.game.MUW_PlayUltimateRecord")
	proto.RegisterType((*MWU_RequestUltimatePlayer)(nil), "ultimate.service.game.MWU_RequestUltimatePlayer")
	proto.RegisterType((*MUW_RequestUltimatePlayer)(nil), "ultimate.service.game.MUW_RequestUltimatePlayer")
	proto.RegisterType((*MWU_ViewFormation)(nil), "ultimate.service.game.MWU_ViewFormation")
	proto.RegisterType((*MUW_ViewFormation)(nil), "ultimate.service.game.MUW_ViewFormation")
	proto.RegisterType((*MUW_CheckInvite)(nil), "ultimate.service.game.MUW_CheckInvite")
	proto.RegisterType((*MWU_CheckInviteResult)(nil), "ultimate.service.game.MWU_CheckInviteResult")
	proto.RegisterType((*MWU_AddInvite)(nil), "ultimate.service.game.MWU_AddInvite")
	proto.RegisterType((*MUW_AddInviteResult)(nil), "ultimate.service.game.MUW_AddInviteResult")
	proto.RegisterType((*MWU_InviteRecharge)(nil), "ultimate.service.game.MWU_InviteRecharge")
	proto.RegisterType((*MUW_InviteRecharge)(nil), "ultimate.service.game.MUW_InviteRecharge")
	proto.RegisterType((*GetPlayerInfoByIDRequest)(nil), "ultimate.service.game.GetPlayerInfoByIDRequest")
	proto.RegisterType((*GetPlayerInfoByIDReply)(nil), "ultimate.service.game.GetPlayerInfoByIDReply")
	proto.RegisterType((*GetGuildInfoByIDRequest)(nil), "ultimate.service.game.GetGuildInfoByIDRequest")
	proto.RegisterType((*GetGuildInfoByIDReply)(nil), "ultimate.service.game.GetGuildInfoByIDReply")
	proto.RegisterType((*PublishBroadCast)(nil), "ultimate.service.game.PublishBroadCast")
	proto.RegisterType((*PublishSendWorldMessage)(nil), "ultimate.service.game.PublishSendWorldMessage")
}

func init() { proto.RegisterFile("game/game.proto", fileDescriptor_2a9278d664c0c01e) }

var fileDescriptor_2a9278d664c0c01e = []byte{
	// 1236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcb, 0x6e, 0x1b, 0x37,
	0x17, 0xfe, 0xc7, 0xb2, 0x6c, 0xcd, 0x91, 0x65, 0x3b, 0x13, 0x5f, 0x26, 0x09, 0x8c, 0x28, 0x0a,
	0xfe, 0x42, 0x2d, 0x5a, 0x07, 0x48, 0xdb, 0x45, 0xbb, 0x4b, 0x1c, 0xc4, 0x15, 0x1a, 0x07, 0xce,
	0x28, 0xae, 0x97, 0x03, 0x7a, 0x48, 0x49, 0x44, 0xe6, 0xa2, 0x90, 0x1c, 0x07, 0x7a, 0x8f, 0xbe,
	0x40, 0xd1, 0x65, 0x9f, 0xa1, 0x6f, 0xd3, 0x87, 0xe8, 0xb2, 0x38, 0x87, 0x94, 0x34, 0x76, 0xe4,
	0x34, 0x81, 0x53, 0xc0, 0x1b, 0xc3, 0xfc, 0xce, 0x99, 0x8f, 0xdf, 0xb9, 0x91, 0x14, 0x6c, 0x0c,
	0x59, 0x26, 0x1e, 0xe1, 0x9f, 0xfd, 0xb1, 0x2a, 0x4c, 0x11, 0x6c, 0x97, 0xa9, 0x91, 0x19, 0x33,
	0x62, 0x5f, 0x0b, 0x75, 0x2e, 0x13, 0xb1, 0x8f, 0xc6, 0xce, 0x5f, 0x2b, 0xb0, 0x71, 0xa0, 0x0a,
	0xad, 0x8f, 0x53, 0x36, 0x11, 0xaa, 0x97, 0x0f, 0x8a, 0xe0, 0x1e, 0xf8, 0x63, 0x5a, 0xc5, 0x92,
	0x87, 0x5e, 0xdb, 0xeb, 0xd6, 0xa2, 0x86, 0x05, 0x7a, 0x3c, 0xd8, 0x85, 0xd5, 0x52, 0x5b, 0xd3,
	0x52, 0xdb, 0xeb, 0xfa, 0xd1, 0x0a, 0x2e, 0x7b, 0x1c, 0xbf, 0x42, 0x66, 0x6b, 0xaa, 0xb5, 0xbd,
	0x6e, 0x2b, 0x6a, 0x58, 0xa0, 0xc7, 0x83, 0x1d, 0x58, 0x19, 0x8a, 0x9c, 0x0b, 0x15, 0x2e, 0xb7,
	0xbd, 0x6e, 0x3d, 0x72, 0xab, 0x20, 0x80, 0x65, 0xc5, 0x12, 0x11, 0xd6, 0x09, 0xa5, 0xff, 0x83,
	0x87, 0xd0, 0x1a, 0x09, 0xc6, 0x63, 0xd4, 0xad, 0x98, 0x34, 0xe1, 0x0a, 0x19, 0xd7, 0x10, 0x3c,
	0x76, 0x58, 0xf0, 0x00, 0x68, 0x1d, 0xbf, 0x2d, 0x59, 0x2a, 0xcd, 0x24, 0x5c, 0x25, 0x9f, 0x26,
	0x62, 0xaf, 0x2c, 0x14, 0xdc, 0x87, 0xa6, 0x0b, 0x23, 0x67, 0x99, 0x08, 0x1b, 0xa4, 0x16, 0x2c,
	0xf4, 0x92, 0x65, 0x22, 0xb8, 0x03, 0x8d, 0x61, 0x29, 0x53, 0x8e, 0x82, 0x7d, 0x0a, 0x73, 0x95,
	0xd6, 0x3d, 0x1e, 0x74, 0x61, 0x33, 0x65, 0xda, 0xc4, 0x69, 0x31, 0x2c, 0x06, 0x83, 0xd8, 0xc8,
	0x4c, 0x84, 0x40, 0x31, 0xad, 0x23, 0xfe, 0x82, 0xe0, 0xd7, 0x32, 0x13, 0x18, 0x59, 0x91, 0xa7,
	0x32, 0x17, 0x61, 0xb3, 0xed, 0x75, 0x1b, 0x91, 0x5b, 0x05, 0x5b, 0x50, 0x4f, 0xc5, 0xb9, 0x48,
	0xc3, 0x35, 0x52, 0x66, 0x17, 0x98, 0xa4, 0x73, 0x39, 0x8e, 0xad, 0xa5, 0x45, 0x96, 0xc6, 0xb9,
	0x1c, 0xbf, 0x20, 0xe3, 0x03, 0x58, 0x73, 0x82, 0x75, 0x52, 0x28, 0x11, 0xae, 0xdb, 0x98, 0x2c,
	0xd6, 0x47, 0x88, 0x72, 0x23, 0xb5, 0x29, 0xd4, 0xc4, 0xf9, 0x6c, 0xb8, 0xdc, 0x58, 0x70, 0xe6,
	0xa4, 0x44, 0xc6, 0x64, 0xae, 0xe3, 0x41, 0x5a, 0x14, 0x2a, 0xdc, 0xb4, 0x4e, 0x0e, 0x7c, 0x8e,
	0x58, 0xd0, 0xc6, 0x04, 0xaa, 0x22, 0x36, 0x93, 0xb1, 0xc0, 0x04, 0xdc, 0x6a, 0xd7, 0xba, 0xad,
	0x08, 0x10, 0x7b, 0x3d, 0x19, 0x8b, 0x1e, 0x0f, 0xf6, 0x00, 0x06, 0x4c, 0x8f, 0x64, 0x91, 0xa3,
	0x3d, 0x20, 0xbb, 0xef, 0x90, 0x1e, 0x0f, 0x3a, 0xd0, 0xca, 0x8a, 0x32, 0x37, 0x33, 0x86, 0xdb,
	0xe4, 0xd1, 0x24, 0xd0, 0x51, 0xb4, 0x61, 0x4d, 0x95, 0xb9, 0x98, 0xb9, 0x6c, 0xd9, 0x4d, 0x10,
	0x9b, 0x6f, 0xa2, 0x0d, 0x33, 0x22, 0x1e, 0xa4, 0x6c, 0x18, 0x6e, 0xb7, 0x6b, 0xdd, 0x7a, 0xe4,
	0x13, 0xf2, 0x3c, 0x65, 0x43, 0x34, 0x8f, 0x05, 0x7b, 0xe3, 0x12, 0xb6, 0x43, 0x71, 0xf8, 0x88,
	0xd8, 0x8c, 0x3d, 0x84, 0xd6, 0x34, 0x63, 0x86, 0x99, 0x52, 0x87, 0xbb, 0x54, 0x23, 0x97, 0xc6,
	0x3e, 0x61, 0x98, 0xd6, 0xa4, 0x54, 0x31, 0x17, 0x49, 0xa1, 0x98, 0x11, 0x61, 0x68, 0xd3, 0x9a,
	0x94, 0xea, 0x99, 0x83, 0xb0, 0xdc, 0x4a, 0x98, 0x52, 0xe5, 0xf1, 0xbc, 0xf1, 0xef, 0x50, 0x47,
	0xac, 0x5b, 0xfc, 0x78, 0xda, 0xfe, 0xdf, 0xc3, 0x2e, 0x35, 0x86, 0x7e, 0x5b, 0x32, 0x25, 0x62,
	0x96, 0x18, 0xcc, 0x0f, 0xf5, 0xc7, 0x5d, 0xda, 0x7b, 0x0b, 0xcd, 0x7d, 0xb2, 0x3e, 0x21, 0x23,
	0x76, 0x49, 0xe7, 0xcf, 0x25, 0x58, 0xa7, 0x31, 0x3b, 0xa4, 0x06, 0xc3, 0x29, 0xab, 0x76, 0x9f,
	0x77, 0xb1, 0xfb, 0xf6, 0x00, 0xac, 0x89, 0x1a, 0xd7, 0x8e, 0x99, 0x4f, 0x08, 0xf5, 0xed, 0x07,
	0x27, 0xed, 0x1e, 0xf8, 0x19, 0xd3, 0xc6, 0x1a, 0x97, 0xed, 0xf0, 0x5a, 0xa0, 0xc7, 0x71, 0x24,
	0x9c, 0x91, 0x98, 0xeb, 0x76, 0x24, 0x2c, 0x44, 0xd4, 0xf7, 0xa1, 0x99, 0x28, 0x81, 0xf5, 0xa0,
	0x90, 0x56, 0x88, 0x1c, 0x2c, 0x44, 0xed, 0xbe, 0x07, 0x30, 0x62, 0x69, 0xea, 0x0a, 0x62, 0xa7,
	0xce, 0x47, 0xc4, 0x16, 0x64, 0x0b, 0xea, 0xb6, 0x2f, 0x1b, 0xb6, 0xeb, 0x69, 0x41, 0x15, 0x60,
	0xda, 0xa4, 0xc2, 0x35, 0xad, 0xef, 0x2a, 0x40, 0x98, 0xed, 0xd9, 0x3d, 0x80, 0x4c, 0x64, 0x67,
	0xa8, 0xac, 0xcc, 0x68, 0xd4, 0xea, 0x91, 0x6f, 0x91, 0x97, 0x65, 0xd6, 0xe9, 0xc3, 0xf6, 0xd1,
	0xe9, 0x49, 0x1c, 0x89, 0xb7, 0xa5, 0xd0, 0xa6, 0x72, 0x56, 0xfd, 0x08, 0xcb, 0x32, 0x1f, 0x14,
	0xa1, 0xd7, 0xae, 0x75, 0x9b, 0x8f, 0xbf, 0xd8, 0x5f, 0x78, 0xca, 0xed, 0x5f, 0x3a, 0xe1, 0x22,
	0xfa, 0x66, 0x4e, 0x3a, 0x4e, 0x59, 0x22, 0x16, 0x92, 0x7a, 0x9f, 0x4c, 0xfa, 0x0a, 0xb6, 0x2a,
	0x4a, 0xe7, 0xe5, 0xfe, 0xe1, 0x82, 0xd0, 0xff, 0x7f, 0x88, 0x73, 0xf6, 0xd1, 0x65, 0x4a, 0xd2,
	0xb9, 0x88, 0xd2, 0xfb, 0x54, 0xca, 0xef, 0x60, 0xfb, 0xe8, 0xe4, 0x74, 0x41, 0x3e, 0xb1, 0x7d,
	0x64, 0xee, 0xca, 0xeb, 0xd9, 0x03, 0x2a, 0x93, 0x39, 0x55, 0xb7, 0xb3, 0x03, 0x5b, 0x95, 0xaf,
	0x66, 0x9c, 0x9d, 0xdf, 0x3c, 0xd8, 0x41, 0x85, 0xc8, 0x73, 0xe2, 0x44, 0x44, 0x38, 0x5b, 0x74,
	0x4a, 0x68, 0x95, 0xc4, 0x97, 0xef, 0x93, 0xa6, 0x56, 0xc9, 0x6c, 0xa6, 0x9c, 0xcf, 0xbc, 0xa7,
	0x97, 0xa8, 0xed, 0xd0, 0xa7, 0x5f, 0x69, 0x6b, 0x45, 0x8c, 0xd3, 0x9e, 0xaf, 0x45, 0x0d, 0x0b,
	0x58, 0x02, 0x8e, 0x33, 0x39, 0x23, 0x58, 0xb6, 0x04, 0x5c, 0x9b, 0x29, 0x81, 0xd5, 0x78, 0x72,
	0x7a, 0xa3, 0x35, 0xfe, 0xe1, 0xc1, 0x9d, 0x4a, 0xf3, 0x4c, 0x65, 0x5a, 0x11, 0x9f, 0x4d, 0xa6,
	0x53, 0x32, 0xe7, 0xb1, 0x52, 0x51, 0x49, 0x95, 0xe7, 0xe3, 0xd4, 0xce, 0xdb, 0xe1, 0x86, 0xab,
	0xfd, 0xdd, 0x83, 0x5b, 0x98, 0xdb, 0x5f, 0xa4, 0x78, 0xf7, 0xbc, 0x50, 0x19, 0xc3, 0xb3, 0xf9,
	0x66, 0xaa, 0x3c, 0x39, 0xbd, 0xe1, 0x2a, 0x8f, 0x60, 0x03, 0x45, 0x1e, 0x8c, 0x44, 0xf2, 0xa6,
	0x97, 0x9f, 0x4b, 0x43, 0x77, 0x52, 0x2e, 0xde, 0x9d, 0x49, 0x51, 0x79, 0x33, 0x5a, 0xc0, 0xde,
	0x67, 0x92, 0xdc, 0x66, 0xc2, 0x6a, 0x91, 0xef, 0x90, 0x1e, 0xef, 0x28, 0x7b, 0x0e, 0x57, 0xe8,
	0x22, 0xa1, 0xcb, 0xd4, 0x5c, 0x87, 0x14, 0xcd, 0x42, 0xa9, 0x42, 0xc5, 0x49, 0xc1, 0x05, 0x05,
	0x5a, 0x8f, 0x7c, 0x42, 0x0e, 0x0a, 0x2e, 0x3a, 0x3f, 0x43, 0x0b, 0xf7, 0x7c, 0xc2, 0xf9, 0x67,
	0x08, 0x60, 0x0c, 0xb7, 0x31, 0x1f, 0x33, 0xb2, 0xff, 0x5e, 0xfe, 0xaf, 0x1e, 0x04, 0xa8, 0x7f,
	0xba, 0x5f, 0x32, 0x62, 0x6a, 0xf8, 0x2f, 0x41, 0xdc, 0x87, 0xa6, 0x33, 0x56, 0x9e, 0x15, 0x60,
	0x21, 0xba, 0xfc, 0x2f, 0x4a, 0xaa, 0x5d, 0x96, 0xf4, 0x00, 0xd6, 0xb8, 0x64, 0x59, 0x91, 0xf3,
	0x78, 0x28, 0x07, 0xc6, 0xbd, 0xe4, 0x9b, 0x0e, 0x3b, 0x94, 0x03, 0x63, 0x65, 0x9d, 0x9c, 0xde,
	0x34, 0x59, 0x5f, 0x41, 0x78, 0x28, 0x2a, 0xb7, 0xdc, 0xd3, 0x49, 0xef, 0x99, 0x3b, 0xb5, 0x82,
	0x75, 0x58, 0x9a, 0x89, 0x5a, 0x92, 0xbc, 0xf3, 0x1a, 0x76, 0x16, 0xf8, 0x8e, 0xd3, 0xc9, 0xb5,
	0x5e, 0x05, 0x5f, 0xc2, 0xee, 0xa1, 0x98, 0xdf, 0x98, 0x1f, 0x12, 0x10, 0xc1, 0xf6, 0xfb, 0xae,
	0xb8, 0xff, 0x35, 0xae, 0xfb, 0x9f, 0x60, 0xf3, 0xb8, 0x3c, 0x4b, 0xa5, 0x1e, 0x3d, 0x55, 0x05,
	0xe3, 0x07, 0x4c, 0x1b, 0x7c, 0x7f, 0x66, 0x7a, 0x68, 0x93, 0xee, 0x51, 0xd2, 0x57, 0x33, 0x3d,
	0x9c, 0xfe, 0x30, 0x42, 0x13, 0x67, 0x86, 0x51, 0x3d, 0xd6, 0xc8, 0xf4, 0x8c, 0x19, 0xd6, 0x89,
	0x61, 0xd7, 0x31, 0xf5, 0x45, 0xce, 0x4f, 0x0b, 0x95, 0xf2, 0x23, 0xa1, 0x35, 0x1b, 0x8a, 0x4a,
	0x20, 0x2d, 0x0c, 0xe4, 0xc2, 0x06, 0x4b, 0x57, 0x6f, 0x50, 0xbb, 0xb0, 0xc1, 0xe3, 0xbf, 0x3d,
	0x68, 0x1e, 0xb2, 0x4c, 0xf4, 0x6d, 0x50, 0x41, 0x09, 0xb7, 0xde, 0xab, 0x47, 0xf0, 0xe8, 0x8a,
	0xe0, 0xaf, 0xaa, 0xf2, 0xdd, 0x6f, 0x3e, 0xfe, 0x83, 0x71, 0x3a, 0xe9, 0xfc, 0x2f, 0x50, 0xb0,
	0x79, 0xb9, 0x0a, 0xc1, 0xfe, 0xd5, 0x24, 0x8b, 0x2a, 0x7b, 0xf7, 0xeb, 0x8f, 0xf6, 0xa7, 0x3d,
	0xcf, 0x56, 0xe8, 0x97, 0xfa, 0xb7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xc1, 0x94, 0x8a,
	0xbc, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GameService service

type GameServiceClient interface {
	GetPlayerInfoByID(ctx context.Context, in *GetPlayerInfoByIDRequest, opts ...client.CallOption) (*GetPlayerInfoByIDReply, error)
	GetGuildInfoByID(ctx context.Context, in *GetGuildInfoByIDRequest, opts ...client.CallOption) (*GetGuildInfoByIDReply, error)
}

type gameServiceClient struct {
	c           client.Client
	serviceName string
}

func NewGameServiceClient(serviceName string, c client.Client) GameServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "ultimate.service.game"
	}
	return &gameServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *gameServiceClient) GetPlayerInfoByID(ctx context.Context, in *GetPlayerInfoByIDRequest, opts ...client.CallOption) (*GetPlayerInfoByIDReply, error) {
	req := c.c.NewRequest(c.serviceName, "GameService.GetPlayerInfoByID", in)
	out := new(GetPlayerInfoByIDReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGuildInfoByID(ctx context.Context, in *GetGuildInfoByIDRequest, opts ...client.CallOption) (*GetGuildInfoByIDReply, error) {
	req := c.c.NewRequest(c.serviceName, "GameService.GetGuildInfoByID", in)
	out := new(GetGuildInfoByIDReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameService service

type GameServiceHandler interface {
	GetPlayerInfoByID(context.Context, *GetPlayerInfoByIDRequest, *GetPlayerInfoByIDReply) error
	GetGuildInfoByID(context.Context, *GetGuildInfoByIDRequest, *GetGuildInfoByIDReply) error
}

func RegisterGameServiceHandler(s server.Server, hdlr GameServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&GameService{hdlr}, opts...))
}

type GameService struct {
	GameServiceHandler
}

func (h *GameService) GetPlayerInfoByID(ctx context.Context, in *GetPlayerInfoByIDRequest, out *GetPlayerInfoByIDReply) error {
	return h.GameServiceHandler.GetPlayerInfoByID(ctx, in, out)
}

func (h *GameService) GetGuildInfoByID(ctx context.Context, in *GetGuildInfoByIDRequest, out *GetGuildInfoByIDReply) error {
	return h.GameServiceHandler.GetGuildInfoByID(ctx, in, out)
}
